#! /bin/sh
if [ "$1" = "-print" ] ; then 
    for plotfile in  short.gcm long.gcm shortc.gcm shortv.gcm blong4.gcm blong32.gcm bcast.gcm dsum.gcm ; do
        destfile=`basename  .gcm`
	# Just in case eps format ... 
        cat ./$plotfile | sed 	 -e 's/terminal postscript eps/terminal postscript/g' | gnuplot 		> ./$destfile.ps
	lpr ./$destfile.ps
    done
else
    for plotfile in  short.gcm long.gcm shortc.gcm shortv.gcm blong4.gcm blong32.gcm bcast.gcm dsum.gcm ; do
        destfile=.gcm
        gnuplot ./$plotfile > ./$destfile.x
    done
fi
