#! /bin/csh
#
# Run the mpptest tests to get communication performance
#
if ($#argv > 1) then
    if ("$1" == "-help") then 
        echo "Run mpptest for round-trip messages from 0 to 1 MByte."
	echo "Output goes to stdout"
        exit
    endif
endif
#
# Round-trip times, blocking (from 0 to 1 MBytes)
mpirun -np 2 -mvhome mpptest -wx 1 2 -wy 2 2 -tgoal 0.1 -auto 
mpirun -np 2 -mvhome mpptest -wx 2 2 -wy 2 2 -tgoal 0.1 -auto \
		-size 1024 16384  256 -autodx 128
mpirun -np 2 -mvhome mpptest -wx 1 2 -wy 1 2 -tgoal 0.5 -auto \
	-size 16384 65536 1024   -autodx 512 -reps 100
mpirun -np 2 -mvhome mpptest -wx 2 2 -wy 1 2 -tgoal 1.0 -auto \
	-size 65536 1048576 8192 -autodx 8192 -reps 25
#
# Nonblocking times
mpirun -np 2 -mvhome mpptest -wx 1 2 -wy 2 2 -async -tgoal 0.1 -auto 
mpirun -np 2 -mvhome mpptest -wx 2 2 -wy 2 2 -async -tgoal 0.1 -auto \
	-size 1024 16384  256    -autodx 128
mpirun -np 2 -mvhome mpptest -wx 1 2 -wy 1 2 -async -tgoal 0.5 -auto \
	-size 16384 65536 1024   -autodx 512 -reps 100
mpirun -np 2 -mvhome mpptest -wx 2 2 -wy 1 2 -async -tgoal 1.0 -auto \
	-size 65536 1048576 8192 -autodx 8192 -reps 25
#
# 
