.TH MPE_Make_color_array 4 "12/6/2001" " " "MPE"
.SH NAME
MPE_Make_color_array \-  Makes an array of color indices 
.SH SYNOPSIS
.nf
#include "mpe.h" 
int MPE_Make_color_array( handle, ncolors, array )
MPE_XGraph handle;
int        ncolors;
MPE_Color  array[];
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B handle 
- MPE graphics handle
.PD 1
.PD 0
.TP
.B nc     
- Number of colors
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B array 
- Array of color indices
.PD 1

.SH NOTES
The new colors for a uniform distribution in hue space and replace the
existing colors 
.B except
for 
.I MPE_WHITE
and 
.I MPE_BLACK
\&.



.SH NOTES FOR FORTRAN INTERFACE 
The Fortran interface to this routine is different from its C
counterpart and it has an additional argument, ierr, at the end
of the argument list, i.e. the returned function value (the error
code) in C interface is returned as the additional argument in
Fortran interface.  The Fortran interface is invoked with the
CALL statement.

All MPI and MPE objects, MPI_Comm, MPE_XGraph and MPE_Color, are
of type INTEGER in Fortran.
.SH LOCATION
mpe_graphics.c
