#! /bin/sh
#
# Setup for ch_meiko and meiko
for arg in $device_args $@ ; do
    case $arg in 
     -u | -usage | --usage | --usag | --usa | --us | --u | -help | --help )
	echo "--with-device=$DEVICE" >&2
	exit 0;
	;;
     *) if test -n "$arg" ; then
	    echo "unrecognized argument $arg"
	    exit 1
	fi
	;;
    esac
done
is_adi1=1
DEFAULT_MACHINE="meiko"
# Jim Cownie claims that -laio is no longer needed ...
if test -s /opt/MEIKOcs2/lib/libmpsc.a ; then
    if test -n "$device_meiko" ; then
        LIB_LIST="$LIB_LIST -L/opt/MEIKOcs2/lib -lew -lelan"
    else
        LIB_LIST="$LIB_LIST -L/opt/MEIKOcs2/lib -lmpsc -lew -lelan"
    fi
else
    print_error "Could not find the library /opt/MEIKOcs2/lib/libmpsc.a"
    print_error "Cannot build MEIKO version"
    exit 1
fi
# This include is needed for the elan.h files
DEVCFLAGS="$DEVCFLAGS -I/opt/MEIKOcs2/include"
# These were recommended by Jim Cownie
if test -z "$OPTFLAGS" ; then
#      OPTFLAGS="-xcg92 -xO2"
     OPTFLAGS="-O"
fi
#RANLIB=true

