.TH mpif77 1 "7/26/2004" " " "MPI Commands"
.SH NAME
mpif77 \-  Compiles and links MPI programs written in Fortran 77 
.SH DESCRIPTION
This command can be used to compile and link MPI programs written in
Fortran 77.  It provides the options and any special libraries that are
needed to compile and link MPI programs.

It is important to use this command (or a 
.I Makefile
processed with
.I mpireconfig
) particularly when linking programs, as it provides
the necessary libraries.  It can also simplify the use of the MPE
profiling libraries, through the use of the 
.I -mpilog
, 
.I -mpitrace
,
and 
.I -mpianim
commands.

.SH COMMAND LINE ARGUMENTS
.PD 0
.TP
.B -mpilog    
- Build version that generate MPE log files
.PD 1
.PD 0
.TP
.B -mpitrace  
- Build version that generates traces
.PD 1
.PD 0
.TP
.B -mpianim   
- Build version that generates real-time
animation
.PD 1
.PD 0
.TP
.B -show      
- Show the commands that would be used without
runnning them
.PD 1
.PD 0
.TP
.B -help      
- Give short help
.PD 1
.PD 0
.TP
.B -echo      
- Show exactly what this program is doing.
This option should normally not be used.
.PD 1
.PD 0
.TP
.B others     
- are passed to the compiler or linker.  For example, 
.I -c
causes files to be compiled, 
.I -g
selects compilation with debugging
on most systems, and 
.I -o name
causes linking with the output
executable given the name 
.I name
\&.

.PD 1

.SH ENVIRONMENT VARIABLES
The environment variables 
.I MPICH_F77
and 
.I MPICH_F77LINKER
may be used
to select different Fortran 77 compiler and linker.  Note that since
MPICH is built with a particular C and Fortran compiler, change the
compilers used can cause problems.  Use this only if you could intermix
code compiled with the different compilers.

.SH EXAMPLES

To compile a single file 
.I foo.f
, use
.nf
mpif77 -c foo.f
.fi


To link the output and make an executable, use
.nf
mpif77 -o foo foo.o
.fi

Combining compilation and linking in a single command
.nf
mpif77 -o foo foo.f
.fi

is a convenient way to build simple programs.

.SH SEE ALSO
mpicc, mpireconfig
.br
.SH LOCATION
/home/MPI/mansrc/commands
