ClusterName=test
SlurmUser=root
SlurmctldHost=localhost
SlurmctldPort=6815
SlurmdPort=6820
AuthType=""

SelectType=select/cons_tres
SelectTypeParameters=CR_Core_Memory
TopologyPlugin=topology/block

NodeName=node[01-32] NodeAddr=localhost Port=40001-40032 feature=block RealMemory=2000
