#Download base image ubuntu 16.04
FROM ubuntu:16.04

# Update Ubuntu Software repository
RUN apt-get update

# Install vim from ubuntu repository
RUN apt-get install -y \
    vim \
    git \
    wget \
    make \
    autoconf \
    gcc \
    python \
    libmunge-dev \
    libmysqlclient-dev \
    libssl-dev
WORKDIR /usr/src/app