.TH MPI_Initialized 3 "11/14/2001" " " "MPI"
.SH NAME
MPI_Initialized \-  Indicates whether 
.I MPI_Init
has been called. 
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Initialized( int *flag )
.fi
.SH OUTPUT PARAMETER
.PD 0
.TP
.B flag 
- Flag is true if 
.I MPI_Init
has been called and false otherwise. 
.PD 1

.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 
.I MPI_WTIME
and 
.I MPI_WTICK
) have
an additional argument 
.I ierr
at the end of the argument list.  
.I ierr
is an integer and has the same meaning as the return value of the routine
in C.  In Fortran, MPI routines are subroutines, and are invoked with the
.I call
statement.

All MPI objects (e.g., 
.I MPI_Datatype
, 
.I MPI_Comm
) are of type 
.I INTEGER
in Fortran.
.SH LOCATION
initialize.c
