.TH MPI_Get_processor_name 3 "11/14/2001" " " "MPI"
.SH NAME
MPI_Get_processor_name \-  Gets the name of the processor 
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Get_processor_name( 
        char *name,
        int *resultlen)
.fi
.SH OUTPUT PARAMETERS
.PD 0
.TP
.B name 
- A unique specifier for the actual (as opposed to virtual) node. This
must be an array of size at least 
.I MPI_MAX_PROCESSOR_NAME
\&.

.PD 1
.PD 0
.TP
.B resultlen 
- Length (in characters) of the name 
.PD 1

.SH NOTES
The name returned should identify a particular piece of hardware;
the exact format is implementation defined.  This name may or may not
be the same as might be returned by 
.I gethostname
, 
.I uname
, or 
.I sysinfo
\&.


.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 
.I MPI_WTIME
and 
.I MPI_WTICK
) have
an additional argument 
.I ierr
at the end of the argument list.  
.I ierr
is an integer and has the same meaning as the return value of the routine
in C.  In Fortran, MPI routines are subroutines, and are invoked with the
.I call
statement.

All MPI objects (e.g., 
.I MPI_Datatype
, 
.I MPI_Comm
) are of type 
.I INTEGER
in Fortran.
.SH LOCATION
getpname.c
