#ifndef MPIJOBDEFS_H
#define MPIJOBDEFS_H

#define MPIJOB_TIMEOUT					10000
#define MPIJOB_CUSTOM_ERROR				1
#define MPIJOB_SUCCESS					0

#define MPIJOB_THRD_CMD_EXIT			1
#define MPIJOB_THRD_CMD_ABORT			2
#define MPIJOB_THRD_CMD_SETEXE			3
#define MPIJOB_THRD_CMD_STARTTRANSFER	4
#define MPIJOB_THRD_CMD_TRANSFER		5
#define MPIJOB_THRD_CMD_FINISHTRANSFER	6
#define MPIJOB_THRD_CMD_LAUNCHJOB		7
#define MPIJOB_THRD_CMD_SETDIR			8
#define MPIJOB_THRD_CMD_SETENV			9
#define MPIJOB_THRD_CMD_SENDBREAK		10

#define MPI_LAUNCH_OPT_NOMPI			0x1
#define MPI_LAUNCH_OPT_FIXEDPORT		0x2

#define MPICHKEY						TEXT("SOFTWARE\\MPICH")
#define LMPICHKEY						L"SOFTWARE\\MPICH"
#define MPICHJOBSKEY					TEXT("SOFTWARE\\MPICH\\Jobs\\")

#define MPICH_IS_KEY					TEXT("ISFinished")

// These definitions must be changed by hand if the projects are re-created and the GUIDs change.
#define MPIJOBSERVERGUIDSTR		TEXT("{33F90D31-2504-11D3-A549-95E3DB6446D2}")
#define MPILAUNCHSERVERGUIDSTR	TEXT("{F710F442-2A3E-11D3-95D5-009027106653}")
#define MPISYSTEMSERVERGUIDSTR	TEXT("{C5B57ACC-36EF-11D3-95DB-009027106653}")

#define MPICONFIGACCESS		0x01
#define MPICONFIGLAUNCH		0x02
#define MPICONFIGPERMIT		0x04
#define MPICONFIGDENY		0x08
#define MPICONFIGSET		0x10
#define MPICONFIGREMOVE		0x20

#define RSH_OUTPUT_STDOUT	0x1
#define RSH_OUTPUT_STDERR	0x2
#define RSH_OUTPUT_MORE		0x4

#endif
