##### User configurable options #####

INSTALL_DIR = #INSTALL_DIR#
CC          = #MPICC#
F77         = #MPIF77#
CLINKER     = #MPICC#
FLINKER     = #MPIF77#
OPTFLAGS    = #OPTFLAGS#
#

### End User configurable options ###

CFLAGS  = #CFLAGS# $(OPTFLAGS)
FFLAGS = #FFLAGS#  $(OPTFLAGS)
LIBS = 
FLIBS =
EXECS = pi3 cpi cpilog

default: cpi pi3

all: $(EXECS)

cpi: cpi.o 
	$(CLINKER) $(OPTFLAGS) -o cpi cpi.o \
	$(LIB_PATH) $(LIB_LIST) -lm

cpilog: cpilog.o 
	$(CLINKER) $(OPTFLAGS) -o cpilog cpilog.o -lmpe -lm

pi3: pi3.o 
	$(FLINKER) $(OPTFLAGS) -o pi3 pi3.o $(FLIBS)


clean:
	rm -f *.o *~ PI* $(EXECS)

.c.o:
	$(CC) $(CFLAGS) -c $*.c
.f.o:
	$(F77) $(FFLAGS) -c $*.f

