############################################################################
# Copyright (C) SchedMD LLC.
############################################################################
"""Test GRES GPU device normalization, merging, sorting, and parsing."""

import ctypes
import pathlib
import re
import shlex
from dataclasses import dataclass

import pytest

import atf

ULONG_BITS = ctypes.sizeof(ctypes.c_ulong) * 8
NVML_CASES = {"a6", "a8", "a10", "a12", "a14", "a16", "a18", "a20"}
FATAL_CASES = {
    "a14",
    "b10",
    "b12",
    "b14",
    "c20",
    "c30",
    "c32",
    "c34",
    "c36",
    "d9",
    "d10",
}


@dataclass(frozen=True)
class GresCfgCase:
    test_id: str
    slurm_conf_gres: str
    gres_conf: str
    fake_gpus_conf: str
    expected_output: tuple[str, ...]
    err_regex: str = ""
    expected_errs: int = 0

    @property
    def requires_nvml(self):
        return self.test_id in NVML_CASES

    @property
    def expect_fatal(self):
        return self.test_id in FATAL_CASES


def _case(
    test_id,
    slurm_conf_gres,
    gres_conf,
    fake_gpus_conf,
    expected_output,
    err_regex="",
    expected_errs=0,
):
    return GresCfgCase(
        test_id,
        slurm_conf_gres,
        gres_conf,
        fake_gpus_conf,
        tuple(
            line
            for line in expected_output.splitlines()
            if line.startswith("GRES_PARSABLE")
        ),
        err_regex,
        int(expected_errs),
    )


def _nvml_affinity_case(test_id, array_length, array_value):
    cpu_count = array_length * ULONG_BITS
    return _case(
        test_id,
        "gpu:1",
        "AutoDetect=nvml",
        f"# This file was autogenerated by test_144_17\n"
        f"tesla|{cpu_count}|~{array_value}|(null)|DEV_PREFIX1\n",
        f"GRES_PARSABLE[gpu](1):(null)|{cpu_count}|0-{cpu_count - 1}|"
        f"(null)|DEV_PREFIX1|HAS_FILE\n",
    )


CASES = [
    _case(
        "a2",
        "gpu:4",
        "",
        "\n# This file was autogenerated by test_144_17\ntesla|4|0-1|(null)|DEV_PREFIX1\ntesla|4|2-3|(null)|DEV_PREFIX3\ntesla|4|2-3|(null)|DEV_PREFIX4\ntesla|4|0-1|(null)|DEV_PREFIX2\n",
        "\nGRES_PARSABLE[gpu](1):(null)|4|0-1|(null)|DEV_PREFIX1|HAS_FILE\nGRES_PARSABLE[gpu](1):(null)|4|0-1|(null)|DEV_PREFIX2|HAS_FILE\nGRES_PARSABLE[gpu](1):(null)|4|2-3|(null)|DEV_PREFIX3|HAS_FILE\nGRES_PARSABLE[gpu](1):(null)|4|2-3|(null)|DEV_PREFIX4|HAS_FILE\n",
    ),
    _case(
        "a4",
        "gpu:8",
        "",
        "\n# This file was autogenerated by test_144_17\ntesla|4|(null)|(null)|(null)\ntesla|4|(null)|(null)|DEV_PREFIX1\ntesla|4|(null)|-1,0|(null)\ntesla|4|(null)|-1,0|DEV_PREFIX3\ntesla|4|0-1|(null)|(null)\ntesla|4|0-1|(null)|DEV_PREFIX2\ntesla|4|0-1|-1,0|(null)\ntesla|4|0-1|-1,0|DEV_PREFIX4\n",
        "\nGRES_PARSABLE[gpu](1):(null)|4|(null)|-1,0|(null)|\nGRES_PARSABLE[gpu](1):(null)|4|0-1|-1,0|(null)|\nGRES_PARSABLE[gpu](1):(null)|4|(null)|(null)|(null)|\nGRES_PARSABLE[gpu](1):(null)|4|0-1|(null)|(null)|\nGRES_PARSABLE[gpu](1):(null)|4|(null)|-1,0|DEV_PREFIX3|HAS_FILE\nGRES_PARSABLE[gpu](1):(null)|4|0-1|-1,0|DEV_PREFIX4|HAS_FILE\nGRES_PARSABLE[gpu](1):(null)|4|(null)|(null)|DEV_PREFIX1|HAS_FILE\nGRES_PARSABLE[gpu](1):(null)|4|0-1|(null)|DEV_PREFIX2|HAS_FILE\n",
    ),
    _nvml_affinity_case("a6", 20, "XXXXXXXXXXXXXXXXXXXX"),
    _nvml_affinity_case("a8", 1, "X"),
    _nvml_affinity_case("a10", 3, "XXX"),
    _nvml_affinity_case("a12", 2**15 // ULONG_BITS, "max"),
    _case(
        "a14",
        "gpu:1",
        "AutoDetect=nvml",
        "\n# This file was autogenerated by test_144_17\ntesla|0|~zero|(null)|DEV_PREFIX1\n",
        "",
        "fatal: _set_cpu_set_bitstr: cpu_set_bitstr is empty",
        "1",
    ),
    _case(
        "a16",
        "gpu:1",
        "AutoDetect=nvml",
        "\n# This file was autogenerated by test_144_17\ntesla|16|~one|(null)|DEV_PREFIX1\n",
        "\nGRES_PARSABLE[gpu](1):(null)|16|0|(null)|DEV_PREFIX1|HAS_FILE\n",
    ),
    _case(
        "a18",
        "gpu:1",
        "AutoDetect=nvml",
        "\n# This file was autogenerated by test_144_17\ntesla|4|~three|(null)|DEV_PREFIX1\n",
        "\nGRES_PARSABLE[gpu](1):(null)|4|0-1|(null)|DEV_PREFIX1|HAS_FILE\n",
    ),
    _case(
        "a20",
        "gpu:1",
        "AutoDetect=nvml",
        "\n# This file was autogenerated by test_144_17\ntesla|16|~half|(null)|DEV_PREFIX1\n",
        "\nGRES_PARSABLE[gpu](1):(null)|16|8-15|(null)|DEV_PREFIX1|HAS_FILE\n",
    ),
    _case(
        "a22",
        "gpu:4",
        "",
        "\n# This file was autogenerated by test_144_17\ntesla_v100-pcie-16gb|4|0-1|(null)|DEV_PREFIX1\ntesla_v100-pcie-16gb|4|2-3|(null)|DEV_PREFIX3\ntesla_v100-pcie-16gb|4|2-3|(null)|DEV_PREFIX4\ntesla_v100-pcie-16gb|4|0-1|(null)|DEV_PREFIX2\n",
        "\nGRES_PARSABLE[gpu](1):(null)|4|0-1|(null)|DEV_PREFIX1|HAS_FILE\nGRES_PARSABLE[gpu](1):(null)|4|0-1|(null)|DEV_PREFIX2|HAS_FILE\nGRES_PARSABLE[gpu](1):(null)|4|2-3|(null)|DEV_PREFIX3|HAS_FILE\nGRES_PARSABLE[gpu](1):(null)|4|2-3|(null)|DEV_PREFIX4|HAS_FILE\n",
    ),
    _case(
        "a24",
        "gpu:v100:4",
        "",
        "\n# This file was autogenerated by test_144_17\ntesla_v100-pcie-16gb|4|0-1|(null)|DEV_PREFIX1\ntesla_v100-pcie-16gb|4|2-3|(null)|DEV_PREFIX3\ntesla_v100-pcie-16gb|4|2-3|(null)|DEV_PREFIX4\ntesla_v100-pcie-16gb|4|0-1|(null)|DEV_PREFIX2\n",
        "\nGRES_PARSABLE[gpu](1):v100|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):v100|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):v100|4|2-3|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):v100|4|2-3|(null)|DEV_PREFIX4|HAS_FILE,HAS_TYPE\n",
    ),
    _case(
        "a26",
        "gpu:TESLA_V100:4",
        "",
        "\n# This file was autogenerated by test_144_17\ntesla_v100-pcie-16gb|4|0-1|(null)|DEV_PREFIX1\ntesla_v100-pcie-16gb|4|2-3|(null)|DEV_PREFIX3\ntesla_v100-pcie-16gb|4|2-3|(null)|DEV_PREFIX4\ntesla_v100-pcie-16gb|4|0-1|(null)|DEV_PREFIX2\n",
        "\nGRES_PARSABLE[gpu](1):TESLA_V100|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):TESLA_V100|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):TESLA_V100|4|2-3|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):TESLA_V100|4|2-3|(null)|DEV_PREFIX4|HAS_FILE,HAS_TYPE\n",
    ),
    _case(
        "a28",
        "gpu:pcie-16gb:4",
        "",
        "\n# This file was autogenerated by test_144_17\ntesla_v100-pcie-16gb|4|0-1|(null)|DEV_PREFIX1\ntesla_v100-pcie-16gb|4|2-3|(null)|DEV_PREFIX3\ntesla_v100-pcie-16gb|4|2-3|(null)|DEV_PREFIX4\ntesla_v100-pcie-16gb|4|0-1|(null)|DEV_PREFIX2\n",
        "\nGRES_PARSABLE[gpu](1):pcie-16gb|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):pcie-16gb|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):pcie-16gb|4|2-3|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):pcie-16gb|4|2-3|(null)|DEV_PREFIX4|HAS_FILE,HAS_TYPE\n",
    ),
    _case(
        "a30",
        "gpu:tesla_v100-pcie-16gb:4",
        "",
        "\n# This file was autogenerated by test_144_17\ntesla_v100-pcie-16gb|4|0-1|(null)|DEV_PREFIX1\ntesla_v100-pcie-16gb|4|2-3|(null)|DEV_PREFIX3\ntesla_v100-pcie-16gb|4|2-3|(null)|DEV_PREFIX4\ntesla_v100-pcie-16gb|4|0-1|(null)|DEV_PREFIX2\n",
        "\nGRES_PARSABLE[gpu](1):tesla_v100-pcie-16gb|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):tesla_v100-pcie-16gb|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):tesla_v100-pcie-16gb|4|2-3|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):tesla_v100-pcie-16gb|4|2-3|(null)|DEV_PREFIX4|HAS_FILE,HAS_TYPE\n",
    ),
    _case(
        "a32",
        "gpu:k20m:1,gpu:k20m1:1,gpu:v100:1",
        "",
        "\n# This file was autogenerated by test_144_17\ntesla_k20m1|4|0-1|(null)|DEV_PREFIX1\ntesla_k20m|4|0-1|(null)|DEV_PREFIX2\ntesla_v100-sxm2-32gb|4|0-1|(null)|DEV_PREFIX3\n",
        "\nGRES_PARSABLE[gpu](1):k20m1|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):k20m|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):v100|4|0-1|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE\n",
    ),
    _case(
        "a34",
        "gpu:p100:1",
        "",
        "\n# This file was autogenerated by test_144_17\nnvidia-p100|4|0-1|(null)|DEV_PREFIX2\nnvidia-p100|4|0-1|(null)|DEV_PREFIX6\nnvidia-p100|4|0-1|(null)|DEV_PREFIX3\nnvidia-p100|4|0-1|(null)|DEV_PREFIX4\nnvidia-p100|4|0-1|(null)|DEV_PREFIX1\nnvidia-p100|4|0-1|(null)|DEV_PREFIX5\n",
        "\nGRES_PARSABLE[gpu](1):p100|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE\n",
    ),
    _case(
        "a36",
        "gpu:aaaa:1,gpu:a:1,gpu:aa:1,gpu:aaa:1",
        "",
        "\n# This file was autogenerated by test_144_17\naa|4|0-1|(null)|DEV_PREFIX2\naaa|4|0-1|(null)|DEV_PREFIX1\na|4|0-1|(null)|DEV_PREFIX3\naaaa|4|0-1|(null)|DEV_PREFIX4\n",
        "\nGRES_PARSABLE[gpu](1):aaa|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):aa|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):a|4|0-1|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):aaaa|4|0-1|(null)|DEV_PREFIX4|HAS_FILE,HAS_TYPE\n",
    ),
    _case(
        "a38",
        "gpu:k20:2,gpu:k20m:4",
        "",
        "\n# This file was autogenerated by test_144_17\nk20|4|0-1|(null)|DEV_PREFIX2\nk20m|4|0-1|(null)|DEV_PREFIX1\nk20|4|0-1|(null)|DEV_PREFIX3\nk20m|4|0-1|(null)|DEV_PREFIX4\nk20|4|0-1|(null)|DEV_PREFIX5\nk20m|4|0-1|(null)|DEV_PREFIX7\nk20|4|0-1|(null)|DEV_PREFIX6\nk20m|4|0-1|(null)|DEV_PREFIX8\n",
        "\nGRES_PARSABLE[gpu](1):k20m|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):k20|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):k20|4|0-1|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):k20m|4|0-1|(null)|DEV_PREFIX4|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):k20m|4|0-1|(null)|DEV_PREFIX7|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):k20m|4|0-1|(null)|DEV_PREFIX8|HAS_FILE,HAS_TYPE\n",
    ),
    _case(
        "a39",
        "gpu:k20:2,gpu:k20m:2",
        "",
        "\n# This file was autogenerated by test_144_17\nk20m|4|0-1|(null)|DEV_PREFIX1\nk20m|4|0-1|(null)|DEV_PREFIX2\nk20m|4|0-1|(null)|DEV_PREFIX3\nk20|4|0-1|(null)|DEV_PREFIX4\nk20|4|0-1|(null)|DEV_PREFIX5\n",
        "\nGRES_PARSABLE[gpu](1):k20m|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):k20m|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):k20|4|0-1|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):k20|4|0-1|(null)|DEV_PREFIX4|HAS_FILE,HAS_TYPE\n",
    ),
    _case(
        "a40",
        "gpu:aaa:3,gpu:bbb:2,gpu:ccc:1",
        "",
        "\n# This file was autogenerated by test_144_17\ntest-bbb-test|4|0-1|(null)|DEV_PREFIX3\ntest-aaa-test|4|0-1|(null)|DEV_PREFIX2\ntest-ccc-test|4|0-1|(null)|DEV_PREFIX5\ntest-aaa-test|4|0-1|(null)|DEV_PREFIX1\ntest-bbb-test|4|0-1|(null)|DEV_PREFIX4\ntest-ccc-test|4|0-1|(null)|DEV_PREFIX6\n",
        "\nGRES_PARSABLE[gpu](1):aaa|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):aaa|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):bbb|4|0-1|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):bbb|4|0-1|(null)|DEV_PREFIX4|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):ccc|4|0-1|(null)|DEV_PREFIX5|HAS_FILE,HAS_TYPE\n",
    ),
    _case(
        "a42",
        "gpu:aaa:1,gpu:aaa:1,gpu:aaa:1",
        "",
        "\n# This file was autogenerated by test_144_17\ntest-aaa-test|4|0-1|(null)|DEV_PREFIX4\ntest-aaa-test|4|0-1|(null)|DEV_PREFIX3\ntest-aaa-test|4|0-1|(null)|DEV_PREFIX2\ntest-aaa-test|4|0-1|(null)|DEV_PREFIX1\n",
        "\nGRES_PARSABLE[gpu](1):aaa|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):aaa|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):aaa|4|0-1|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE\n",
    ),
    _case(
        "a52",
        "gpu:tesla:3,gpu:special:1",
        "",
        "\n# This file was autogenerated by test_144_17\ntesla|4|0-1|-1|DEV_PREFIX0\ntesla|4|0-1|-1|DEV_PREFIX1\ntesla|4|0-1|-1|DEV_PREFIX2\n",
        "\nGRES_PARSABLE[gpu](1):tesla|4|0-1|-1|DEV_PREFIX0|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):tesla|4|0-1|-1|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):tesla|4|0-1|-1|DEV_PREFIX2|HAS_FILE,HAS_TYPE\n",
    ),
    _case(
        "a53",
        "gpu:tesla:3,gpu:special:1",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=special File=DEV_PREFIX5\n",
        "\n# This file was autogenerated by test_144_17\ntesla|4|0-1|-1|DEV_PREFIX0\ntesla|4|0-1|-1|DEV_PREFIX1\ntesla|4|0-1|-1|DEV_PREFIX2\n",
        "\nGRES_PARSABLE[gpu](1):tesla|4|0-1|-1|DEV_PREFIX0|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):tesla|4|0-1|-1|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):tesla|4|0-1|-1|DEV_PREFIX2|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):special|4|(null)|(null)|DEV_PREFIX5|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "a54",
        "gpu:tesla:3,gpu:special:1",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla File=DEV_PREFIX1 Cores=0\nName=gpu Type=special File=DEV_PREFIX5\n",
        "\n# This file was autogenerated by test_144_17\ntesla|4|0-1|-1|DEV_PREFIX0\ntesla|4|0-1|-1|DEV_PREFIX1\ntesla|4|0-1|-1|DEV_PREFIX2\n",
        "\nGRES_PARSABLE[gpu](1):tesla|4|0-1|-1|DEV_PREFIX0|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):tesla|4|0-1|-1|DEV_PREFIX2|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):special|4|(null)|(null)|DEV_PREFIX5|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "a55",
        "gpu:tesla:3,gpu:special:1",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla File=DEV_PREFIX[0-2] Cores=0-1\nName=gpu Type=tesla File=DEV_PREFIX3 Cores=0\nName=gpu Type=special File=DEV_PREFIX5\n",
        "\n# This file was autogenerated by test_144_17\ntesla|4|0-1|-1|DEV_PREFIX0\ntesla|4|0-1|-1|DEV_PREFIX1\ntesla|4|0-1|-1|DEV_PREFIX2\n",
        "\nGRES_PARSABLE[gpu](1):tesla|4|0-1|-1|DEV_PREFIX0|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):tesla|4|0-1|-1|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):tesla|4|0-1|-1|DEV_PREFIX2|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):special|4|(null)|(null)|DEV_PREFIX5|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
        "warning: A line in gres.conf for GRES \\S+ has [0-9]+ more configured than expected in slurm.conf",
        "1",
    ),
    _case(
        "a56",
        "gpu:tesla:4,gpu:special:1",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla File=DEV_PREFIX[0-3] Cores=0-1\nName=gpu Type=special File=DEV_PREFIX5\n",
        "\n# This file was autogenerated by test_144_17\ntesla|4|0-1|-1|DEV_PREFIX0\ntesla|4|0-1|-1|DEV_PREFIX1\ntesla|4|0-1|-1|DEV_PREFIX2\n",
        "\nGRES_PARSABLE[gpu](1):tesla|4|0-1|-1|DEV_PREFIX0|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):tesla|4|0-1|-1|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):tesla|4|0-1|-1|DEV_PREFIX2|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):tesla|4|0-1|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):special|4|(null)|(null)|DEV_PREFIX5|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "a57",
        "",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla File=DEV_PREFIX[0-3] Cores=0-1\nName=gpu Type=special File=DEV_PREFIX5\n",
        "\n# This file was autogenerated by test_144_17\ntesla|4|0-1|-1|DEV_PREFIX0\ntesla|4|0-1|-1|DEV_PREFIX1\ntesla|4|0-1|-1|DEV_PREFIX2\n",
        "",
        "warning: A line in gres.conf for GRES \\S+ has [0-9]+ more configured than expected in slurm.conf",
        "2",
    ),
    _case(
        "a58",
        "gpu:tesla:3,gpu:special:1,tmpdisk:100",
        "",
        "",
        "\nGRES_PARSABLE[tmpdisk](100):(null)|4|(null)|(null)|(null)|CountOnly\n",
    ),
    _case(
        "a59",
        "gpu:tesla:2,gpu:gtx:1",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla File=DEV_PREFIX[0-4]\nName=gpu Type=tesla File=DEV_PREFIX5\nName=gpu Type=special File=DEV_PREFIX6\nName=gpu Type=gtx File=DEV_PREFIX7\nName=nic Count=100\nName=tmpdisk Count=10G\n",
        "\n# This file was autogenerated by test_144_17\ntesla|4|0-1|-1|DEV_PREFIX0\ntesla|4|0-1|-1|DEV_PREFIX1\ntesla|4|0-1|-1|DEV_PREFIX2\n",
        "\nGRES_PARSABLE[gpu](1):tesla|4|0-1|-1|DEV_PREFIX0|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):tesla|4|0-1|-1|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):gtx|4|(null)|(null)|DEV_PREFIX7|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
        "warning: A line in gres.conf for GRES \\S+ has [0-9]+ more configured than expected in slurm.conf",
        "5",
    ),
    _case(
        "a60",
        "gpu:tesla:4",
        "",
        "\n# This file was autogenerated by test_144_17\ntesla|4|0-1|(null)|DEV_PREFIX1|MIG-GPU-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/7/0\ntesla|4|0-1|(null)|DEV_PREFIX2|MIG-GPU-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/10/0\ntesla|4|2-3|(null)|DEV_PREFIX3|MIG-GPU-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/8/0\ntesla|4|2-3|(null)|DEV_PREFIX4|MIG-GPU-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/9/0\n",
        "\nGRES_PARSABLE[gpu](1):tesla|4|0-1|(null)|DEV_PREFIX1|MIG-GPU-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/7/0|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):tesla|4|0-1|(null)|DEV_PREFIX2|MIG-GPU-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/10/0|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):tesla|4|2-3|(null)|DEV_PREFIX3|MIG-GPU-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/8/0|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):tesla|4|2-3|(null)|DEV_PREFIX4|MIG-GPU-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/9/0|HAS_FILE,HAS_TYPE\n",
    ),
    _case(
        "b2",
        "gpu:tesla:1,gpu:1080:1,gpu:gtx560:1,mps:300",
        "",
        "\n# This file was autogenerated by test_144_17\ntesla|4|0-1|(null)|DEV_PREFIX1\n1080ti|4|0-1|(null)|DEV_PREFIX2\ngtx560|4|0-1|(null)|DEV_PREFIX0\n",
        "\nGRES_PARSABLE[mps](100):gtx560|4|0-1|(null)|DEV_PREFIX0|HAS_FILE,HAS_TYPE,SHARED,ONE_SHARING\nGRES_PARSABLE[gpu](1):gtx560|4|0-1|(null)|DEV_PREFIX0|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[mps](100):tesla|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,SHARED,ONE_SHARING\nGRES_PARSABLE[gpu](1):tesla|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[mps](100):1080|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE,SHARED,ONE_SHARING\nGRES_PARSABLE[gpu](1):1080|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE\n",
    ),
    _case(
        "b4",
        "gpu:ti:3,gpu:gtx:3",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=ti File=DEV_PREFIX0 COREs=0\nName=gpu Type=ti File=DEV_PREFIX[1-2] COREs=0-1\nName=gpu Type=gtx File=DEV_PREFIX[3-5] COREs=0-1 Links=-1,0,0,0,0,0\n",
        "\n# This file was autogenerated by test_144_17\n1080ti|4|0-1|(null)|DEV_PREFIX0\n1080ti|4|0-1|(null)|DEV_PREFIX1\n1080ti|4|0-1|(null)|DEV_PREFIX2\ngtx560|4|0-1|0,0,0,-1,0,0|DEV_PREFIX3\ngtx560|4|0-1|0,0,0,0,-1,0|DEV_PREFIX4\ngtx560|4|0-1|-1,0,0,0,0,0|DEV_PREFIX5\n",
        "\nGRES_PARSABLE[gpu](1):gtx|4|0-1|-1,0,0,0,0,0|DEV_PREFIX5|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):ti|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):ti|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE\n",
        "error: This GPU specified in \\[slurm\\|gres\\].conf has mismatching Cores, Links or UUID",
        "3",
    ),
    _case(
        "b5",
        "gpu:a100:8",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=a100 File=DEV_PREFIX0 COREs=0-1  Links=0,0,0,-1,0,0,0,0\nName=gpu Type=a100 File=DEV_PREFIX1 COREs=0-1  Links=0,0,-1,0,0,0,0,0\nName=gpu Type=a100 File=DEV_PREFIX2 COREs=0-1  Links=0,-1,0,0,0,0,0,0\nName=gpu Type=a100 File=DEV_PREFIX3 COREs=0-1  Links=-1,0,0,0,0,0,0,0\nName=gpu Type=a100 File=DEV_PREFIX4 COREs=2-3 Links=0,0,0,0,0,0,0,-1\nName=gpu Type=a100 File=DEV_PREFIX5 COREs=2-3 Links=0,0,0,0,0,0,-1,0\nName=gpu Type=a100 File=DEV_PREFIX6 COREs=2-3 Links=0,0,0,0,0,-1,0,0\nName=gpu Type=a100 File=DEV_PREFIX7 COREs=2-3 Links=0,0,0,0,-1,0,0,0\n",
        "\n# This file was autogenerated by test_144_17\na100|4|0-1|-1,0,0,0,0,0,0,0|DEV_PREFIX3\na100|4|0-1|0,-1,0,0,0,0,0,0|DEV_PREFIX2\na100|4|0-1|0,0,-1,0,0,0,0,0|DEV_PREFIX1\na100|4|0-1|0,0,0,-1,0,0,0,0|DEV_PREFIX0\na100|4|2-3|0,0,0,0,-1,0,0,0|DEV_PREFIX7\na100|4|2-3|0,0,0,0,0,-1,0,0|DEV_PREFIX6\na100|4|2-3|0,0,0,0,0,0,-1,0|DEV_PREFIX5\na100|4|2-3|0,0,0,0,0,0,0,-1|DEV_PREFIX4\n",
        "\nGRES_PARSABLE[gpu](1):a100|4|0-1|-1,0,0,0,0,0,0,0|DEV_PREFIX3|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):a100|4|0-1|0,-1,0,0,0,0,0,0|DEV_PREFIX2|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):a100|4|0-1|0,0,-1,0,0,0,0,0|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):a100|4|0-1|0,0,0,-1,0,0,0,0|DEV_PREFIX0|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):a100|4|2-3|0,0,0,0,-1,0,0,0|DEV_PREFIX7|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):a100|4|2-3|0,0,0,0,0,-1,0,0|DEV_PREFIX6|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):a100|4|2-3|0,0,0,0,0,0,-1,0|DEV_PREFIX5|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):a100|4|2-3|0,0,0,0,0,0,0,-1|DEV_PREFIX4|HAS_FILE,HAS_TYPE\n",
    ),
    _case(
        "b6",
        "gpu:1080:3",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=1080 File=DEV_PREFIX[0-2] COREs=0-1\n",
        "",
        "\nGRES_PARSABLE[gpu](1):1080|4|0-1|(null)|DEV_PREFIX0|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):1080|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):1080|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "b7",
        "gpu:a100:8",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=a100 File=DEV_PREFIX0 COREs=0-1  Links=0,0,0,-1\nName=gpu Type=a100 File=DEV_PREFIX1 COREs=0-1  Links=0,0,-1,0\nName=gpu Type=a100 File=DEV_PREFIX2 COREs=0-1  Links=0,-1,0,0\nName=gpu Type=a100 File=DEV_PREFIX3 COREs=0-1  Links=-1,0,0,0\nName=gpu Type=a100 File=DEV_PREFIX4 COREs=2-3\nName=gpu Type=a100 File=DEV_PREFIX5 COREs=2-3\nName=gpu Type=a100 File=DEV_PREFIX6 COREs=2-3\nName=gpu Type=a100 File=DEV_PREFIX7 COREs=2-3\n",
        "\n# This file was autogenerated by test_144_17\na100|4|0-1|-1,0,0,0|DEV_PREFIX3\na100|4|0-1|0,-1,0,0|DEV_PREFIX2\na100|4|0-1|0,0,-1,0|DEV_PREFIX1\na100|4|0-1|0,0,0,-1|DEV_PREFIX0\na100|4|2-3|(null)|DEV_PREFIX7\na100|4|2-3|(null)|DEV_PREFIX6\na100|4|2-3|(null)|DEV_PREFIX5\na100|4|2-3|(null)|DEV_PREFIX4\n",
        "\nGRES_PARSABLE[gpu](1):a100|4|0-1|-1,0,0,0|DEV_PREFIX3|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):a100|4|0-1|0,-1,0,0|DEV_PREFIX2|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):a100|4|0-1|0,0,-1,0|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):a100|4|0-1|0,0,0,-1|DEV_PREFIX0|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):a100|4|2-3|(null)|DEV_PREFIX4|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):a100|4|2-3|(null)|DEV_PREFIX5|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):a100|4|2-3|(null)|DEV_PREFIX6|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):a100|4|2-3|(null)|DEV_PREFIX7|HAS_FILE,HAS_TYPE\n",
    ),
    _case(
        "b8",
        "gpu:5",
        "\n# This file was autogenerated by test_144_17\nName=gpu File=DEV_PREFIX[0-1] Cores=0,1\nName=gpu File=DEV_PREFIX[2-3] Cores=0,1 Links=-1\nName=gpu File=DEV_PREFIX4 Cores=0\n",
        "",
        "\nGRES_PARSABLE[gpu](1):(null)|4|0,1|-1|DEV_PREFIX2|HAS_FILE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):(null)|4|0,1|-1|DEV_PREFIX3|HAS_FILE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):(null)|4|0,1|(null)|DEV_PREFIX0|HAS_FILE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):(null)|4|0,1|(null)|DEV_PREFIX1|HAS_FILE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):(null)|4|0|(null)|DEV_PREFIX4|HAS_FILE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "b10",
        "gpu:tesla:1,gpu:1",
        "",
        "",
        "",
        "GRES in slurm.conf have a type while others do not",
        "1",
    ),
    _case(
        "b12",
        "gpu:tesla:2,gpu:v100:2",
        "\n# This file was autogenerated by test_144_17\nName=gpu            File=DEV_PREFIX[0-1]\nName=gpu Type=v100  File=DEV_PREFIX[2-3]\n",
        "",
        "",
        'fatal: gres.conf for \\S+, some records have "Type=" specification while others do not',
        "1",
    ),
    _case(
        "b14",
        "gpu:tesla:2,gpu:v100:2",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla  File=DEV_PREFIX[0-1]\nName=gpu Type=v100\n",
        "",
        "",
        'fatal: gres.conf for \\S+, some records have "File" specification while others do not',
        "1",
    ),
    _case(
        "c2",
        "gpu:tesla:1,gpu:gtx560:1,mps:200",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=gtx560 File=DEV_PREFIX0 COREs=0,1\nName=gpu Type=tesla File=DEV_PREFIX1 COREs=2,3\nName=mps Count=100 File=DEV_PREFIX1\nName=mps Count=100 File=DEV_PREFIX0\n",
        "",
        "\nGRES_PARSABLE[mps](100):gtx560|4|0,1|(null)|DEV_PREFIX0|HAS_FILE,HAS_TYPE,SHARED,ONE_SHARING\nGRES_PARSABLE[gpu](1):gtx560|4|0,1|(null)|DEV_PREFIX0|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[mps](100):tesla|4|2,3|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,SHARED,ONE_SHARING\nGRES_PARSABLE[gpu](1):tesla|4|2,3|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "c4",
        "gpu:tesla:1,gpu:gtx560:1,mps:210",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla File=DEV_PREFIX1 COREs=2,3\nName=gpu Type=gtx560 File=DEV_PREFIX0 COREs=0,1\nName=mps Count=210\n",
        "",
        "\nGRES_PARSABLE[mps](105):gtx560|4|0,1|(null)|DEV_PREFIX0|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT,SHARED,ONE_SHARING\nGRES_PARSABLE[gpu](1):gtx560|4|0,1|(null)|DEV_PREFIX0|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[mps](105):tesla|4|2,3|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT,SHARED,ONE_SHARING\nGRES_PARSABLE[gpu](1):tesla|4|2,3|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "c6",
        "gpu:tesla:3",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla File=DEV_PREFIX[3-4] Cores=2-3\nName=gpu Type=tesla File=DEV_PREFIX1 Cores=0-1\n",
        "\n# This file was autogenerated by test_144_17\ntesla|4|0-1|(null)|DEV_PREFIX1\ntesla|4|0-1|(null)|DEV_PREFIX2\ntesla|4|2-3|(null)|DEV_PREFIX3\ntesla|4|2-3|(null)|DEV_PREFIX4\n",
        "\nGRES_PARSABLE[gpu](1):tesla|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):tesla|4|2-3|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):tesla|4|2-3|(null)|DEV_PREFIX4|HAS_FILE,HAS_TYPE\n",
    ),
    _case(
        "c8",
        "gpu:tesla:6",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla File=DEV_PREFIX1 Cores=2-3\nName=gpu Type=tesla File=DEV_PREFIX2 Cores=2-3\nName=gpu Type=tesla File=DEV_PREFIX3 Cores=2-3\nName=gpu Type=tesla File=DEV_PREFIX4 Cores=2-3\n",
        "\n# This file was autogenerated by test_144_17\ntesla|4|0-1|(null)|DEV_PREFIX5\ntesla|4|0-1|(null)|DEV_PREFIX6\n",
        "\nGRES_PARSABLE[gpu](1):tesla|4|2-3|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|2-3|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|2-3|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|2-3|(null)|DEV_PREFIX4|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|0-1|(null)|DEV_PREFIX5|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):tesla|4|0-1|(null)|DEV_PREFIX6|HAS_FILE,HAS_TYPE\n",
    ),
    _case(
        "c10",
        "gpu:tesla:8",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla File=DEV_PREFIX0 Cores=0-3 Links=-1,2,2,0,0,0,0,0\nName=gpu Type=tesla File=DEV_PREFIX1 Cores=0-3 Links=2,-1,2,0,0,0,0,0\nName=gpu Type=tesla File=DEV_PREFIX2 Cores=0-3 Links=2,2,-1,0,0,0,0,0\nName=gpu Type=tesla File=DEV_PREFIX3 Cores=0-3 Links=0,0,0,-1,0,1,0,0\nName=gpu Type=tesla File=DEV_PREFIX4 Cores=0-3 Links=0,0,0,0,-1,1,0,0\nName=gpu Type=tesla File=DEV_PREFIX5 Cores=0-3 Links=0,0,0,1,1,-1,0,0\nName=gpu Type=tesla File=DEV_PREFIX6 Cores=0-3 Links=0,0,0,0,0,0,-1,2\nName=gpu Type=tesla File=DEV_PREFIX7 Cores=0-3 Links=0,0,0,0,0,0,2,-1\n",
        "",
        "\nGRES_PARSABLE[gpu](1):tesla|4|0-3|-1,2,2,0,0,0,0,0|DEV_PREFIX0|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|0-3|2,-1,2,0,0,0,0,0|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|0-3|2,2,-1,0,0,0,0,0|DEV_PREFIX2|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|0-3|0,0,0,-1,0,1,0,0|DEV_PREFIX3|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|0-3|0,0,0,0,-1,1,0,0|DEV_PREFIX4|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|0-3|0,0,0,1,1,-1,0,0|DEV_PREFIX5|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|0-3|0,0,0,0,0,0,-1,2|DEV_PREFIX6|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|0-3|0,0,0,0,0,0,2,-1|DEV_PREFIX7|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "c12",
        "",
        "",
        "",
        "",
    ),
    _case(
        "c14",
        "gpu:tesla:4",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla File=DEV_PREFIX[1-4] Cores=2-3\n",
        "",
        "\nGRES_PARSABLE[gpu](1):tesla|4|2-3|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|2-3|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|2-3|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|2-3|(null)|DEV_PREFIX4|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "c16",
        "gpu:tesla:1,tmpdisk:disky:1,nic:nikki:1,mic:mickey:1",
        "\n# This file was autogenerated by test_144_17\nName=gpu     Type=tesla File=DEV_PREFIX1 Cores=0-3\nName=tmpdisk Type=disky File=DEV_PREFIX2 Cores=0-3\nName=nic     Type=nikki File=DEV_PREFIX3 Cores=0-3\nName=mic     Type=mickey File=DEV_PREFIX4 Cores=0-3\n",
        "",
        "\nGRES_PARSABLE[nic](1):nikki|4|0-3|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[mic](1):mickey|4|0-3|(null)|DEV_PREFIX4|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[tmpdisk](1):disky|4|0-3|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):tesla|4|0-3|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "c17",
        "gpu:1,tmpdisk:1,nic:1,mic:1",
        "\n# This file was autogenerated by test_144_17\nName=gpu     File=DEV_PREFIX1 Cores=0-3\nName=tmpdisk File=DEV_PREFIX2 Cores=0-3\nName=nic     File=DEV_PREFIX3 Cores=0-3\nName=mic     File=DEV_PREFIX4 Cores=0-3\n",
        "",
        "\nGRES_PARSABLE[nic](1):(null)|4|0-3|(null)|DEV_PREFIX3|HAS_FILE\nGRES_PARSABLE[mic](1):(null)|4|0-3|(null)|DEV_PREFIX4|HAS_FILE\nGRES_PARSABLE[tmpdisk](1):(null)|4|0-3|(null)|DEV_PREFIX2|HAS_FILE\nGRES_PARSABLE[gpu](1):(null)|4|0-3|(null)|DEV_PREFIX1|HAS_FILE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "c18",
        "gpu:tesla:2",
        "\n# This file was autogenerated by test_144_17\nNodeName=tux0 Name=gpu     Type=tesla File=DEV_PREFIX1 Cores=0-3\nNodeName=tux0              Type=tesla File=DEV_PREFIX2 Cores=0-3\n",
        "",
        "\nGRES_PARSABLE[gpu](1):tesla|4|0-3|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
        "error: Invalid GRES data, no type name",
        "1",
    ),
    _case(
        "c20",
        "",
        "\n# This file was autogenerated by test_144_17\nType=tesla File=DEV_PREFIX1 Cores=0-3\n",
        "",
        "",
        "error: _parse_next_key: Parsing error at unrecognized key",
        "1",
    ),
    _case(
        "c22",
        "tmpdisk:10g",
        "Name=tmpdisk count=10g",
        "",
        "\nGRES_PARSABLE[tmpdisk](10737418240):(null)|4|(null)|(null)|(null)|\n",
    ),
    _case(
        "c23",
        "tmpdisk:tempy:10g",
        "Name=tmpdisk Type=tempy Count=10g Cores=0-1",
        "",
        "\nGRES_PARSABLE[tmpdisk](10737418240):tempy|4|0-1|(null)|(null)|HAS_TYPE\n",
    ),
    _case(
        "c24",
        "gpu:a:2,gpu:b:2",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=a File=DEV_PREFIX1 Cores=0-3\nName=gpu Type=a File=DEV_PREFIX2 Cores=0-3\nName=gpu Type=b File=DEV_PREFIX5 Cores=0-3\nName=gpu Type=b File=DEV_PREFIX6 Cores=0-3\n",
        "",
        "\nGRES_PARSABLE[gpu](1):a|4|0-3|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):a|4|0-3|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):b|4|0-3|(null)|DEV_PREFIX5|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):b|4|0-3|(null)|DEV_PREFIX6|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "c28",
        "gpu:tesla_a:4,gpu:tesla_b:4",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla_a File=DEV_PREFIX[1-2] Cores=0-3\nName=gpu Type=tesla_b File=DEV_PREFIX[3-4] Cores=0-3\nName=gpu Type=tesla_a File=DEV_PREFIX5       Cores=0-3\nName=gpu Type=tesla_b File=DEV_PREFIX6       Cores=0-3\nName=gpu Type=tesla_a File=DEV_PREFIX7       Cores=0-3\nName=gpu Type=tesla_b File=DEV_PREFIX8       Cores=0-3\n",
        "",
        "\nGRES_PARSABLE[gpu](1):tesla_a|4|0-3|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla_a|4|0-3|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla_b|4|0-3|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla_b|4|0-3|(null)|DEV_PREFIX4|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla_a|4|0-3|(null)|DEV_PREFIX5|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla_b|4|0-3|(null)|DEV_PREFIX6|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla_a|4|0-3|(null)|DEV_PREFIX7|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla_b|4|0-3|(null)|DEV_PREFIX8|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "c30",
        "gpu:tesla:6",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla File=DEV_PREFIX3       Cores=0-3\nName=gpu Type=tesla File=DEV_PREFIX3       Cores=0-3\nName=gpu Type=tesla File=DEV_PREFIX4       Cores=0-3\nName=gpu Type=tesla File=DEV_PREFIX4       Cores=0-3\nName=gpu Type=tesla File=DEV_PREFIX[3-4] Cores=0-3\n",
        "",
        "",
        "error: gpu duplicate device file name",
        "1",
    ),
    _case(
        "c32",
        "gpu:tesla:10",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla File=DEV_PREFIX1       Cores=0-3\nName=gpu Type=tesla File=DEV_PREFIX[1-2] Cores=0-3\nName=gpu Type=tesla File=DEV_PREFIX[1-3] Cores=0-3\nName=gpu Type=tesla File=DEV_PREFIX[1-4] Cores=0-3\n",
        "",
        "",
        "error: gpu duplicate device file name",
        "1",
    ),
    _case(
        "c34",
        "gpu:tesla:10",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla File=DEV_PREFIX4       Cores=0-3\nName=gpu Type=tesla File=DEV_PREFIX[3-4] Cores=0-3\nName=gpu Type=tesla File=DEV_PREFIX[2-4] Cores=0-3\nName=gpu Type=tesla File=DEV_PREFIX[1-4] Cores=0-3\n",
        "",
        "",
        "error: gpu duplicate device file name",
        "1",
    ),
    _case(
        "c36",
        "gpu:tesla:4",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla File=DEV_PREFIX1 Cores=0\nName=gpu Type=tesla File=DEV_PREFIX1 Cores=0-1\nName=gpu Type=tesla File=DEV_PREFIX1 Cores=0-2\nName=gpu Type=tesla File=DEV_PREFIX1 Cores=0-3\n",
        "",
        "",
        "error: gpu duplicate device file name",
        "1",
    ),
    _case(
        "c38",
        "gpu:tesla:4",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla File=DEV_PREFIX1 Cores=0\nName=gpu Type=tesla File=DEV_PREFIX2 Cores=0-1\nName=gpu Type=tesla File=DEV_PREFIX3 Cores=0-2\nName=gpu Type=tesla File=DEV_PREFIX4 Cores=0-3\n",
        "",
        "\nGRES_PARSABLE[gpu](1):tesla|4|0|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|0-2|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|0-3|(null)|DEV_PREFIX4|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "c40",
        "gpu:tesla:4",
        '\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla File=DEV_PREFIX1 Cores=0-3\nName=gpu Type=tesla File=DEV_PREFIX2 Cores=0-3 Links=""\nName=gpu Type=tesla File=DEV_PREFIX3 Cores=0-3 Links=null\nName=gpu Type=tesla File=DEV_PREFIX4 Cores=0-3 Links=0\n',
        "",
        "\nGRES_PARSABLE[gpu](1):tesla|4|0-3|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|0-3|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|0-3|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|0-3|(null)|DEV_PREFIX4|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
        "error: gres.conf: Ignoring invalid Link",
        "3",
    ),
    _case(
        "c42",
        "gpu:tesla:4",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla File=DEV_PREFIX1 Cores=0-3 Links=0-1\nName=gpu Type=tesla File=DEV_PREFIX2 Cores=0-3 Links=0,-1\nName=gpu Type=tesla File=DEV_PREFIX3 Cores=0-3 Links=0-2\nName=gpu Type=tesla File=DEV_PREFIX4 Cores=0-3 Links=0,-1,2\n",
        "",
        "\nGRES_PARSABLE[gpu](1):tesla|4|0-3|0,-1|DEV_PREFIX2|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|0-3|0,-1,2|DEV_PREFIX4|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|0-3|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|0-3|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "c46",
        "gpu:4",
        "\n# This file was autogenerated by test_144_17\nName=gpu File=DEV_PREFIX1 Cores=0-3\nName=gpu File=DEV_PREFIX2 Cores=0-3\nName=gpu File=DEV_PREFIX3 Cores=0-3\nName=gpu File=DEV_PREFIX4 Cores=0-3\n\n",
        "",
        "\nGRES_PARSABLE[gpu](1):(null)|4|0-3|(null)|DEV_PREFIX1|HAS_FILE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):(null)|4|0-3|(null)|DEV_PREFIX2|HAS_FILE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):(null)|4|0-3|(null)|DEV_PREFIX3|HAS_FILE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):(null)|4|0-3|(null)|DEV_PREFIX4|HAS_FILE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "c48",
        "gpu:tesla:5",
        '\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla File=DEV_PREFIX1\nName=gpu Type=tesla File=DEV_PREFIX2\nName=gpu Type=tesla File=DEV_PREFIX3 Cores=""\nName=gpu Type=tesla File=DEV_PREFIX4 Cores=null\nName=gpu Type=tesla File=DEV_PREFIX5 Cores=0\n',
        "",
        "\nGRES_PARSABLE[gpu](1):tesla|4|(null)|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|(null)|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4||(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|null|(null)|DEV_PREFIX4|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|0|(null)|DEV_PREFIX5|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "c50",
        "gpu:gtx560:1,gpu:tesla:1,mps:200",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=gtx560 File=DEV_PREFIX0 COREs=0,1\nName=gpu Type=tesla File=DEV_PREFIX1 COREs=2,3\nName=mps Count=100 File=DEV_PREFIX0\nName=mps Count=100 File=DEV_PREFIX1\n",
        "",
        "\nGRES_PARSABLE[mps](100):gtx560|4|0,1|(null)|DEV_PREFIX0|HAS_FILE,HAS_TYPE,SHARED,ONE_SHARING\nGRES_PARSABLE[gpu](1):gtx560|4|0,1|(null)|DEV_PREFIX0|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[mps](100):tesla|4|2,3|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,SHARED,ONE_SHARING\nGRES_PARSABLE[gpu](1):tesla|4|2,3|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "c52",
        "gpu:tesla:3",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla File=DEV_PREFIX[0-1] COREs=0,1\n# NOTE: nvidia2 device is out of service\n# Name=gpu Type=tesla File=DEV_PREFIX[2-3] COREs=2,3\nName=gpu Type=tesla File=DEV_PREFIX3 COREs=2,3\n",
        "",
        "\nGRES_PARSABLE[gpu](1):tesla|4|0,1|(null)|DEV_PREFIX0|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|0,1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):tesla|4|2,3|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "c54",
        "gpu:4",
        "\n# This file was autogenerated by test_144_17\n## Explicitly specify devices on nodes tux0-tux15\n# NodeName=tux[0-15] Name=gpu File=DEV_PREFIX[0-3]\n# NOTE: tux3 DEV_PREFIX1 device is out of service\nNodeName=tux[0-2] Name=gpu File=DEV_PREFIX[0-3]\nNodeName=tux3 Name=gpu File=DEV_PREFIX[0,2-3]\nNodeName=tux[4-15] Name=gpu File=DEV_PREFIX[0-3]\n",
        "",
        "\nGRES_PARSABLE[gpu](1):(null)|4|(null)|(null)|DEV_PREFIX0|HAS_FILE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):(null)|4|(null)|(null)|DEV_PREFIX1|HAS_FILE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):(null)|4|(null)|(null)|DEV_PREFIX2|HAS_FILE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):(null)|4|(null)|(null)|DEV_PREFIX3|HAS_FILE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "c56",
        "gpu:gtx560:1,gpu:tesla:2,mps:900",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=tesla File=DEV_PREFIX1 COREs=2,3\nName=gpu Type=gtx560 File=DEV_PREFIX0 COREs=0,1\nName=gpu Type=tesla File=DEV_PREFIX3 COREs=2,3\nName=mps Count=200 File=DEV_PREFIX1\nName=mps Count=300 File=DEV_PREFIX3\nName=mps Count=400 File=DEV_PREFIX8\n",
        "",
        "\nGRES_PARSABLE[mps](0):gtx560|4|0,1|(null)|DEV_PREFIX0|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT,SHARED,ONE_SHARING\nGRES_PARSABLE[gpu](1):gtx560|4|0,1|(null)|DEV_PREFIX0|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[mps](200):tesla|4|2,3|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,SHARED,ONE_SHARING\nGRES_PARSABLE[gpu](1):tesla|4|2,3|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[mps](300):tesla|4|2,3|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE,SHARED,ONE_SHARING\nGRES_PARSABLE[gpu](1):tesla|4|2,3|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "d1",
        "gpu:a100:4",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=a100 File=DEV_PREFIX0 Cores=0-1\nName=gpu Type=a100 File=DEV_PREFIX1 Cores=0-1\nName=gpu Type=a100 File=DEV_PREFIX2 Cores=0-1\nName=gpu Type=a100 File=DEV_PREFIX3 Cores=0-1\n",
        "",
        "\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX0|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI,ENV_ONEAPI,ENV_OPENCL,ENV_DEFAULT\n",
    ),
    _case(
        "d2",
        "gpu:a100:4",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=a100 File=DEV_PREFIX0 Cores=0-1 Flags=no_gpu_env\nName=gpu Type=a100 File=DEV_PREFIX1 Cores=0-1 Flags=no_gpu_env\nName=gpu Type=a100 File=DEV_PREFIX2 Cores=0-1 Flags=no_gpu_env\nName=gpu Type=a100 File=DEV_PREFIX3 Cores=0-1 Flags=no_gpu_env\n",
        "",
        "\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX0|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE\n",
    ),
    _case(
        "d3",
        "gpu:a100:4",
        "\n# This file was autogenerated by test_144_17\nNodeName=tux0      Name=gpu Type=a100 File=DEV_PREFIX0 Cores=0-1 Flags=amd_gpu_env\nNodeName=tux0      Name=gpu Type=a100 File=DEV_PREFIX1 Cores=0-1 Flags=amd_gpu_env\nNodeName=tux1 Name=gpu Type=a100 File=DEV_PREFIX2 Cores=0-1 Flags=nvidia_gpu_env\nNodeName=tux1 Name=gpu Type=a100 File=DEV_PREFIX3 Cores=0-1 Flags=nvidia_gpu_env\n",
        "",
        "\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX0|HAS_FILE,HAS_TYPE,ENV_RSMI\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_RSMI\n",
    ),
    _case(
        "d4",
        "gpu:a100:4",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=a100 File=DEV_PREFIX0       Cores=0-1 Flags=no_gpu_env\nName=gpu Type=a100 File=DEV_PREFIX[1-3] Cores=0-1 Flags=no_gpu_env\n",
        "\n# This file was autogenerated by test_144_17\na100|4|0-1|(null)|DEV_PREFIX0|(null)|nvidia_gpu_env\n",
        "\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX0|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE\n",
    ),
    _case(
        "d5",
        "gpu:a100:4",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=a100 File=DEV_PREFIX0       Cores=0-1 Flags=nvidia_gpu_env\nName=gpu Type=a100 File=DEV_PREFIX[1-3] Cores=0-1 Flags=nvidia_gpu_env\n",
        "\n# This file was autogenerated by test_144_17\na100|4|0-1|(null)|DEV_PREFIX0|(null)|nvidia_gpu_env\n",
        "\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX0|HAS_FILE,HAS_TYPE,ENV_NVML\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE,ENV_NVML\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE,ENV_NVML\n",
    ),
    _case(
        "d6",
        "gpu:a100:4",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=a100 File=DEV_PREFIX[1-3] Cores=0-1 Flags=nvidia_gpu_env\n",
        "\n# This file was autogenerated by test_144_17\na100|4|0-1|(null)|DEV_PREFIX0|(null)|nvidia_gpu_env\n",
        "\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX0|HAS_FILE,HAS_TYPE,ENV_NVML\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE,ENV_NVML\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE,ENV_NVML\n",
    ),
    _case(
        "d8",
        "gpu:a100:4",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=a100 File=DEV_PREFIX0 Cores=0-1 Flags=amd_gpu_env,nvidia_gpu_env\nName=gpu Type=a100 File=DEV_PREFIX1 Cores=0-1\nName=gpu Type=a100 File=DEV_PREFIX2 Cores=0-1\nName=gpu Type=a100 File=DEV_PREFIX3 Cores=0-1\n",
        "",
        "\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX0|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE,ENV_NVML,ENV_RSMI\n",
    ),
    _case(
        "d9",
        "gpu:a100:4",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=a100 File=DEV_PREFIX[0-1] Cores=0-1 Flags=no_gpu_env\nName=gpu Type=a100 File=DEV_PREFIX[2-3] Cores=0-1 Flags=nvidia_gpu_env\n",
        "",
        "",
        "fatal: Invalid GRES record name=\\S+ type=\\S+: Flags \\(\\S+\\) does not match env flags for previous GRES of same node and name",
        "1",
    ),
    _case(
        "d10",
        "gpu:a100:4",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=a100 File=DEV_PREFIX0       Cores=0-1\nName=gpu Type=a100 File=DEV_PREFIX[1-3] Cores=0-1 Flags=nvidia_gpu_env\n",
        "\n# This file was autogenerated by test_144_17\na100|4|0-1|(null)|DEV_PREFIX0|(null)|nvidia_gpu_env\n",
        "",
        "fatal: Invalid GRES record name=\\S+ type=\\S+: Flags \\(\\S+\\) does not match env flags for previous GRES of same node and name",
        "1",
    ),
    _case(
        "d11",
        "gpu:a100:1,gpu:b100:1,gpu:c100:1,gpu:d100:1",
        "\n# This file was autogenerated by test_144_17\nName=gpu Type=a100 File=DEV_PREFIX0 Cores=0-1 Flags=amd_gpu_env\nName=gpu Type=b100 File=DEV_PREFIX1 Cores=0-1\nName=gpu Type=c100 File=DEV_PREFIX2 Cores=0-1\nName=gpu Type=d100 File=DEV_PREFIX3 Cores=0-1\n",
        "",
        "\nGRES_PARSABLE[gpu](1):a100|4|0-1|(null)|DEV_PREFIX0|HAS_FILE,HAS_TYPE,ENV_RSMI\nGRES_PARSABLE[gpu](1):b100|4|0-1|(null)|DEV_PREFIX1|HAS_FILE,HAS_TYPE,ENV_RSMI\nGRES_PARSABLE[gpu](1):c100|4|0-1|(null)|DEV_PREFIX2|HAS_FILE,HAS_TYPE,ENV_RSMI\nGRES_PARSABLE[gpu](1):d100|4|0-1|(null)|DEV_PREFIX3|HAS_FILE,HAS_TYPE,ENV_RSMI\n",
    ),
]


def _case_params():
    """Attach per-case skip marks. b4 asserts the UUID-aware mismatch text."""
    nvml_build = _is_nvml_build()
    params = []
    for case in CASES:
        marks = []
        if case.test_id == "b4":
            marks.append(
                pytest.mark.skipif(
                    atf.get_version("sbin/slurmd") < (26, 11),
                    reason="MR 4271: GPU mismatch error includes UUID as of 26.11",
                )
            )
        if case.requires_nvml:
            marks.append(
                pytest.mark.skipif(
                    not nvml_build,
                    reason="MR 4271: case needs Slurm built with NVML support",
                )
            )
        params.append(pytest.param(case, id=case.test_id, marks=marks))
    return params


def _is_nvml_build():
    config_h = pathlib.Path(atf.properties["slurm-build-dir"]) / "config.h"
    if not config_h.exists():
        return False
    return bool(re.search(r"^#define\s+HAVE_NVML\s+1$", config_h.read_text(), re.M))


@pytest.fixture(scope="module")
def environment():
    test_dir = atf.module_tmp_path
    test_program = test_dir / "test_144_17"
    source_file = pathlib.Path(__file__).with_suffix(".c")
    atf.compile_against_libslurm(
        str(source_file), str(test_program), full=True, fatal=True
    )
    (test_dir / "slurm.conf").write_text(
        "ControlMachine=test_machine\n"
        "ClusterName=test_cluster\n"
        "GresTypes=gpu,mps,nic,mic,tmpdisk\n"
    )
    for device_index in range(9):
        (test_dir / f"nvidia{device_index}").touch()
    return test_program, test_dir


@pytest.mark.parametrize("case", _case_params())
def test_gres_device_merge(environment, case):
    """Test gres.conf records merged with detected GPU devices."""
    test_program, test_dir = environment
    device_prefix = str(test_dir / "nvidia")
    (test_dir / "gres.conf").write_text(
        case.gres_conf.replace("DEV_PREFIX", device_prefix)
    )
    (test_dir / "fake_gpus.conf").write_text(
        case.fake_gpus_conf.replace("DEV_PREFIX", device_prefix)
    )

    result = atf.run_command(
        shlex.join(
            [str(test_program), str(test_dir), "tux0", case.slurm_conf_gres, "3"]
        ),
    )
    stderr = result["stderr"]

    actual_output = re.findall(r"GRES_PARSABLE\S+", stderr)
    expected_output = [
        line.replace("DEV_PREFIX", device_prefix) for line in case.expected_output
    ]
    assert actual_output == expected_output, (
        f"{case.test_id}: GRES_PARSABLE output mismatch\n"
        f"actual: {actual_output!r}\nexpected: {expected_output!r}\n"
        f"stderr:\n{stderr}"
    )

    if case.err_regex:
        actual_errs = len(re.findall(case.err_regex, stderr))
        assert actual_errs == case.expected_errs, (
            f"{case.test_id}: expected {case.expected_errs} matches of "
            f"{case.err_regex!r}, got {actual_errs}\nstderr:\n{stderr}"
        )

    if case.expect_fatal:
        assert (
            result["exit_code"] != 0
        ), f"{case.test_id}: expected a nonzero exit code\nstderr:\n{stderr}"
    else:
        assert result["exit_code"] == 0, (
            f"{case.test_id}: unexpected exit code {result['exit_code']}\n"
            f"stderr:\n{stderr}"
        )
