# Generated automatically from Makefile.in by configure.
#
#  $Id: Makefile.ch_p4,v 1.1.1.1 1997/09/17 20:39:36 gropp Exp $
#
#  (C) 1995 by Argonne National Laboratory and Mississipi State University.
#      All rights reserved.  See COPYRIGHT in top-level directory.
#
##### User configurable options #####
ARCH        = sun4
COMM        = ch_p4
MPIR_HOME   = /home/MPI/mpich
CC          = gcc -Wall -Wstrict-prototypes -Wmissing-prototypes
CLINKER     = gcc -Wl,-y_MALLOC 
CCC         = 
CCLINKER    = $(CCC)
F77         = f77
FLINKER     = f77
AR          = ar crl
RANLIB      = ranlib
OPTFLAGS    = -g
LIB_PATH    = 
FLIB_PATH   = 
LIB_LIST    = 
#
INCLUDE_DIR =  -I$(MPIR_HOME)/include 
DEVICE      = ch_p4
### End User configurable options ###
LIBS = $(LIB_PATH) $(LIB_LIST) $(LIBNAME) $(LIB_LIST)
ALL: $(EXECS)
.SUFFIXES: .o .cpp .c

EXECS = aditest1 aditest2 aditest3 aditest4 aditest5 aditest6 aditest7 \
	aditest8 aditest9 aditest10 timers trunc
OTHERLIBS = /home/MPI/mpich/mpid/ch_p4/p4-1.4/lib/libp4.a
LIBNAME  = ../$(COMM)/libmpid.a $(OTHERLIBS)
CFLAGS   =  -DFORTRANUNDERSCORE  -DMPE_USE_EXTENSIONS=1 -DHAS_XDR=1  -DHAVE_STDLIB_H=1 -DHAVE_SYSTEM=1 -DHAVE_NICE=1 $(OPTFLAGS) -I../.. -I../../include -I./ -I../$(COMM) \
		-I../ch2

ALL: $(EXECS)

clean:
	/bin/rm -f *~ *.o $(EXECS) 

.c.o:
	$(CC) $(CFLAGS) $(BASEOPT) -c $*.c $(MPI_PROFILE)

.c.cpp:
	cpp $(CFLAGS) $*.c > $*.cpp

timers: timers.o $(LIBS)
	-$(CLINKER) -o timers $(OPTFLAGS) timers.o $(LIBS)
	if [ ! -x timers ] ; then /bin/rm -f timers ; fi
trunc: trunc.o $(LIBS)
	-$(CLINKER) -o trunc $(OPTFLAGS) trunc.o $(LIBS) ./libmpi.a
	if [ ! -x trunc ] ; then /bin/rm -f trunc ; fi
aditest1: aditest1.o check.o testsup.o $(LIBS)
	-$(CLINKER) -o aditest1 $(OPTFLAGS) aditest1.o check.o testsup.o $(LIBS)
	if [ ! -x aditest1 ] ; then /bin/rm -f aditest1 ; fi
aditest2: aditest2.o check.o testsup.o $(LIBS)
	-$(CLINKER) -o aditest2 $(OPTFLAGS) aditest2.o check.o testsup.o $(LIBS)
	if [ ! -x aditest2 ] ; then /bin/rm -f aditest2 ; fi
aditest3: aditest3.o check.o testsup.o $(LIBS)
	-$(CLINKER) -o aditest3 $(OPTFLAGS) aditest3.o check.o testsup.o $(LIBS)
	if [ ! -x aditest3 ] ; then /bin/rm -f aditest3 ; fi
aditest4: aditest4.o check.o testsup.o $(LIBS)
	-$(CLINKER) -o aditest4 check.o testsup.o $(OPTFLAGS) aditest4.o $(LIBS)
	if [ ! -x aditest4 ] ; then /bin/rm -f aditest4 ; fi
aditest5: aditest5.o check.o testsup.o $(LIBS)
	-$(CLINKER) -o aditest5 check.o testsup.o $(OPTFLAGS) aditest5.o $(LIBS)
	if [ ! -x aditest5 ] ; then /bin/rm -f aditest5 ; fi
aditest6: aditest6.o check.o testsup.o $(LIBS)
	-$(CLINKER) -o aditest6 check.o testsup.o $(OPTFLAGS) aditest6.o $(LIBS)
	if [ ! -x aditest6 ] ; then /bin/rm -f aditest6 ; fi
aditest7: aditest7.o check.o testsup.o $(LIBS)
	-$(CLINKER) -o aditest7 check.o testsup.o $(OPTFLAGS) aditest7.o $(LIBS)
	if [ ! -x aditest7 ] ; then /bin/rm -f aditest7 ; fi
aditest8: aditest8.o check.o testsup.o $(LIBS)
	-$(CLINKER) -o aditest8 check.o testsup.o $(OPTFLAGS) aditest8.o $(LIBS)
	if [ ! -x aditest8 ] ; then /bin/rm -f aditest8 ; fi
aditest9: aditest9.o check.o testsup.o $(LIBS)
	-$(CLINKER) -Wl,-M -Wl,-y_MPID_Type_swap_inplace \
	-o aditest9 check.o testsup.o $(OPTFLAGS) aditest9.o $(LIBS) \
		./libmpi.a
	if [ ! -x aditest9 ] ; then /bin/rm -f aditest9 ; fi
#		-L/home/MPI/mpich/lib/sun4/ch_p4 -lmpi
aditest10: aditest10.o check.o testsup.o $(LIBS)
	-$(CLINKER) -o aditest10 check.o $(OPTFLAGS) aditest10.o $(LIBS) \
		./libmpi.a
	if [ ! -x aditest10 ] ; then /bin/rm -f aditest10 ; fi

runtests:
	./timers -p4pg pgt
	./aditest1 -p4pg pg1
	./aditest1 -p4pg pg1 -len 2000 -mpipktsize 1000
	./aditest2 -p4pg pg2
	./aditest2 -p4pg pg2 -len 2000 -mpipktsize 1000
	./aditest3 -p4pg pg3
	./aditest3 -p4pg pg3 -len 2000 -mpipktsize 1000
	./aditest4 -p4pg pg4
	./aditest4 -p4pg pg4 -len 2000 -mpipktsize 1000
	./aditest5 -p4pg pg5
	./aditest5 -p4pg pg5 -len 2000 -mpipktsize 1000
	./aditest6 -p4pg pg6
	./aditest6 -p4pg pg6 -len 2000 -mpipktsize 1000
	./aditest7 -p4pg pg7
	./aditest7 -p4pg pg7 -len 2000 -mpipktsize 1000
	./aditest8 -p4pg pg8
	./aditest8 -p4pg pg8 -len 2000 -mpipktsize 1000
	./aditest9 -p4pg pg9
	./aditest9 -p4pg pg9 -mpixdr
	./aditest9 -p4pg pg9 -len 2000 -mpipktsize 1000
	./aditest9 -p4pg pg9 -mpixdr -len 2000 -mpipktsize 1000
	./aditest10 -p4pg pg10
	./aditest10 -p4pg pg10 -mpixdr
	./aditest10 -p4pg pg10 -len 2000 -mpipktsize 1000
	./aditest10 -p4pg pg10 -mpixdr -len 2000 -mpipktsize 1000
	./trunc -p4pg pgtr
