.TH CLOG_csync 4 "11/5/2003" " " "MPE"
.SH NAME
CLOG_csync \-  synchronize clocks for adjusting times in merge 
.SH SYNOPSIS
.nf
void CLOG_csync( root, diffs )
int root;
double diffs[];
.fi
This version is sequential and non-scalable.  The root process serially
synchronizes with each slave, using the first algorithm in Gropp, "Scalable
clock synchronization on distributed processors without a common clock".
The array is calculated on the root but broadcast and returned on all
processes.

.SH INOUT PARAMETERS

.PD 0
.TP
.B root      
- process to serve as master
.PD 1
.PD 0
.TP
.B timediffs 
- array of doubles to be filled in
.PD 1

.SH LOCATION
clog_merge.c
