.TH CLOG_treesetup 4 "11/5/2003" " " "MPE"
.SH NAME
CLOG_treesetup \-  locally determine parent and children in binary tree 
.SH SYNOPSIS
.nf
void CLOG_treesetup( self, numprocs, myparent, mylchild, myrchild)
int self, numprocs, *myparent, *mylchild, *myrchild;
.fi
Input parameters

.PD 0
.TP
.B self 
- calling process's id
.PD 1
.PD 0
.TP
.B np   
- total number of processes in tree
.PD 1

Output parameters

.PD 0
.TP
.B parent 
- parent in binary tree (or -1 if root)
.PD 1
.PD 0
.TP
.B lchild 
- left child in binary tree (or -1 if none)
.PD 1
.PD 0
.TP
.B rchild 
- right child in binary tree (or -1 if none)
.PD 1

.SH LOCATION
clog_merge.c
