.TH MPE_Describe_state 4 "11/5/2003" " " "MPE"
.SH NAME
MPE_Describe_state \-  Create log record describing a state 
.SH SYNOPSIS
.nf
int MPE_Describe_state( start, end, name, color )
int start, end;
char *name, *color;
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B start 
- event number for the start of the state
.PD 1
.PD 0
.TP
.B end   
- event number for the end of the state
.PD 1
.PD 0
.TP
.B name  
- Name of the state
.PD 1
.PD 0
.TP
.B color 
- color to display the state in
.PD 1

.SH NOTES
Adds string containing a state def to the logfile.  The format of the
definition is (in ALOG)
.nf
(LOG_STATE_DEF) 0 sevent eevent 0 0 "color" "name"
.fi

States are added to a log file by calling 
.I MPE_Log_event
for the start and
end event numbers.

.SH SEE ALSO
MPE_Log_get_event_number
.br
.SH LOCATION
mpe_log.c
