.TH MPE_TagsEnd 4 "6/14/2000" " " "MPE"
.SH NAME
MPE_TagsEnd \-  Returns the private keyval.   
.SH SYNOPSIS
.nf
int MPE_TagsEnd()
.fi
.SH NOTES
This routine is provided to aid in cleaning up all of the allocated
storage in and MPI program.  Normally, this routine does 
.B not
need
to be called.  If it is, it should be called immediately before
.I MPI_Finalize
\&.

.SH LOCATION
privtags.c
