.TH MPE_Init_log 4 "11/5/2003" " " "MPE"
.SH NAME
MPE_Init_log \-  Initialize for logging 
.SH SYNOPSIS
.nf
int MPE_Init_log()
.fi
.SH NOTES
Initializes the MPE logging package.  This must be called before any of
the other MPE logging routines.  It is collective over 
.I MPI_COMM_WORLD


.SH SEE ALSO
MPE_Finish_log
.br
.SH LOCATION
mpe_log.c
