.TH MPE_Decomp1d 4 "6/14/2000" " " "MPE"
.SH NAME
MPE_Decomp1d \-  Compute a balanced decomposition of a 1-D array 
.SH SYNOPSIS
.nf
int MPE_Decomp1d( n, size, rank, s, e )
int n, size, rank, *s, *e;
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B n  
- Length of the array
.PD 1
.PD 0
.TP
.B size 
- Number of processors in decomposition
.PD 1
.PD 0
.TP
.B rank 
- Rank of this processor in the decomposition (0 <= rank < size)
.PD 1

.SH OUTPUT PARAMETERS
.PD 0
.TP
.B s,e 
- Array indices are s:e, with the original array considered as 1:n.  
.PD 1
.SH LOCATION
decomp.c
