.TH MPE_Draw_points 4 "12/6/2001" " " "MPE"
.SH NAME
MPE_Draw_points \-  Draws points on an X Windows display  
.SH SYNOPSIS
.nf
#include "mpe.h" 
int MPE_Draw_points( handle, points, npoints )
MPE_XGraph handle;
MPE_Point *points;
int npoints;
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B handle 
- MPE graphics handle 
.PD 1
.PD 0
.TP
.B points 
- list of points to draw
.PD 1
.PD 0
.TP
.B npoints 
- number of points to draw
.PD 1


.SH NOTES FOR FORTRAN INTERFACE 
The Fortran interface to this routine is different from its C
counterpart and it has an additional argument, ierr, at the end
of the argument list, i.e. the returned function value (the error
code) in C interface is returned as the additional argument in
Fortran interface.  The Fortran interface is invoked with the
CALL statement.

All MPI and MPE objects, MPI_Comm, MPE_XGraph and MPE_Color, are
of type INTEGER in Fortran.
.SH LOCATION
mpe_graphics.c
