.TH MPE_Add_RGB_color 4 "12/6/2001" " " "MPE"
.SH NAME
MPE_Add_RGB_color \-  Adds a color to the colormap given its RGB values 
.SH SYNOPSIS
.nf
#include "mpe.h" 
int MPE_Add_RGB_color( graph, red, green, blue, mapping )
MPE_XGraph graph;
int red, green, blue;
MPE_Color *mapping;
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B graph 
- MPE graphics handle
.PD 1
.PD 0
.TP
.B red, green, blue 
- color levels from 0 to 65535
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B mapping 
- index of the new color
.PD 1

.SH RETURN VALUES
.PD 0
.TP
.B -1 
- maxcolors too large (equal to numcolors)
.PD 1
.PD 0
.TP
.B MPE_SUCCESS 
- successful
.PD 1
.PD 0
.TP
.B mapping 
- index of the new color
.PD 1

.SH NOTES
This call adds a color cell to X11's color table, increments maxcolors
(the index), and writes it to the mapping parameter.


.SH NOTES FOR FORTRAN INTERFACE 
The Fortran interface to this routine is different from its C
counterpart and it has an additional argument, ierr, at the end
of the argument list, i.e. the returned function value (the error
code) in C interface is returned as the additional argument in
Fortran interface.  The Fortran interface is invoked with the
CALL statement.

All MPI and MPE objects, MPI_Comm, MPE_XGraph and MPE_Color, are
of type INTEGER in Fortran.
.SH LOCATION
mpe_graphics.c
