#!/bin/bash
#
# Purpose: Test of SLURM functionality
#          Executes the full battery of tests.
#
# Output:  "Failures:#\nCompletions:#" with a count of tests executed successfully 
#          and failures respectively. The exit code is zero only if all tests 
#          executed successfully.
#

FAILURES=0
COMPLETIONS=0

# Remove any recently edited back-up files
/bin/rm -f test*.*% test*input test*output test*error 

# Run the tests in this directory
/bin/date
for TEST in test[0-9].*[0-9]
do
	expect $TEST
	if [ $? -eq 0 ]
	then
		COMPLETIONS=$((COMPLETIONS+1))
	else
		FAILURES=$((FAILURES+1))
	fi
	/bin/echo "============================================"
done

# Report the results
/bin/date
echo ""
echo ""
echo "Completions:$COMPLETIONS"
echo "Failures:   $FAILURES"

if [ $FAILURES -eq 0 ]
then
	/bin/rm -f test*input test*output test*error 
	exit 0
else
	exit 1
fi
