.TH tstmachines 1 "7/26/2004" " " "MPI Commands"
.SH NAME
tstmachines \-  Tests the availability of remote machines for runing MPI programs 
.SH DESCRIPTION
This script runs some simple tests to test that the environment can
support the 
.I ch_p4
device.

If no parameters are supplied, the default machinefile is used.  This
is either 
.I <mpichhome>/util/machines/machines.$arch
, where 
.I $arch
is
the architecture name returned by 
.I tarch
if MPICH has not be installed or
the data directory (typically  
.I <prefix>/share
) if MPICH has been
installed.

.SH COMMAND LINE ARGUMENTS

.PD 0
.TP
.B -v 
- Turn on verbose mode
.PD 1
.PD 0
.TP
.B -echo 
- Turns on debugging
.PD 1
.PD 0
.TP
.B -machinefile=<filename> 
- Use 
.I filename
instead of the default machinefile
.PD 1
.PD 0
.TP
.B -help 
- Print out a short usage message   
.PD 1

.SH LOCATION
/home/MPI/mansrc/commands
