.TH CLOG_procbuf 4 "11/5/2003" " " "MPE"
.SH NAME
CLOG_procbuf \-  postprocess a buffer of log records before merging 
.SH SYNOPSIS
.nf
void CLOG_procbuf( buf )
double *buf;
.fi
This function fills in fields in log records that were left out during
actual logging to save memory accesses.  Typical fields are the process
id and the lengths of records that are known by predefined type.  This is
also where we will adjust timestamps.

Input parameter

.PD 0
.TP
.B address of the buffer to be processed
- 
.PD 1
.SH LOCATION
clog_merge.c
