.TH MPE_ReturnTags 4 "6/14/2000" " " "MPE"
.SH NAME
MPE_ReturnTags \-  Returns tags allocated with MPE_GetTags. 
.SH SYNOPSIS
.nf
int MPE_ReturnTags( comm, first_tag, ntags )
MPI_Comm comm;
int      first_tag, ntags;
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B comm 
- Communicator to return tags to
.PD 1
.PD 0
.TP
.B first_tag 
- First of the tags to return
.PD 1
.PD 0
.TP
.B ntags 
- Number of tags to return.
.PD 1

.SH SEE ALSO
MPE_GetTags
.br

.SH LOCATION
privtags.c
