.TH SLURMD "8" "June 2006" "slurmd 1.1" "Slurm components"
.SH "NAME"
slurmd \- The compute node daemon for SLURM.
.SH "SYNOPSIS"
\fBslurmd\fR [\fIOPTIONS\fR...]
.SH "DESCRIPTION"
\fBslurmd\fR is the compute node daemon of Slurm. It monitors all tasks 
running on the compute node , accepts work (tasks), launches tasks, and kills 
running tasks upon request.
.TP
OPTIONS
.TP
\fB\-c\fR
Clear system locks as needed. This may be required if \fBslurmd\fR terminated 
abnormally.
.TP
\fB\-D\fR
Run slurmd in the foreground. Error and debug messages will be copied to stderr.
.TP
\fB\-M\fR
Lock slurmd pages into system memory using mlockall(2) to disable
paging of the slurmd process. This may help in cases where nodes are
marked DOWN during periods of heavy swap activity. If the mlockall(2)
system call is not available, an error will be printed to the log
and slurmd will continue as normal.
.TP
\fB\-h\fR
Help; print a brief summary of command options.
.TP
\fB\-f <file>\fR
Read configuration from the specified file. See \fBNOTES\fR below.
.TP
\fB\-L <file>\fR
Write log messages to the specified file.
.TP
\fB\-v\fR
Verbose operation. Multiple \-v's increase verbosity.
.TP
\fB\-V\fR
Print version information and exit.

.SH "ENVIRONMENT VARIABLES"
The following environment variables can be used to override settings
compiled into slurmd.
.TP 20
\fBSLURM_CONF\fR
The location of the SLURM configuration file.  This is overridden by
explicitly naming a configuration file on the command line.

.SH "NOTES"
It may be useful to experiment with different \fBslurmd\fR specific
configuration parameters using a distinct configuration file
(e.g. timeouts).  However, this special configuration file will not be
used by the \fBslurmctld\fR daemon or the Slurm programs, unless you
specifically tell each of them to use it. If you desire changing
communication ports, the location of the temporary file system, or
other parameters used by other Slurm components, change the common
configuration file, \fBslurm.conf\fR.

.SH "COPYING"
Copyright (C) 2002\-2006 The Regents of the University of California.
Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
CODE\-OCEC\-09\-009. All rights reserved.
.LP
This file is part of SLURM, a resource management program.
For details, see <https://computing.llnl.gov/linux/slurm/>.
.LP
SLURM is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 2 of the License, or (at your option)
any later version.
.LP
SLURM is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
details.

.SH "FILES"
.LP
/etc/slurm.conf
.SH "SEE ALSO"
\fBslurm.conf\fR(5), \fBslurmctld\fR(8)
