.TH chp4_servs 1 "7/26/2004" " " "MPI Commands"
.SH NAME
chp4_servs \-  Starts the P4 secure servers on machines known to MPICH 
.SH DESCRIPTION
This script can be used 
.B when there is a working remote shell program
to start the secure servers that the 
.I ch_p4
device can use to speed
up process startup.
.SH LOCATION
/home/MPI/mansrc/commands
