.TH MPI_Pcontrol 3 "11/14/2001" " " "MPI"
.SH NAME
MPI_Pcontrol \-  Controls profiling 
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Pcontrol( int level )
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B level 
- Profiling level 
.PD 1

.SH NOTES
This routine provides a common interface for profiling control.  The
interpretation of 
.I level
and any other arguments is left to the
profiling library.

.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 
.I MPI_WTIME
and 
.I MPI_WTICK
) have
an additional argument 
.I ierr
at the end of the argument list.  
.I ierr
is an integer and has the same meaning as the return value of the routine
in C.  In Fortran, MPI routines are subroutines, and are invoked with the
.I call
statement.

All MPI objects (e.g., 
.I MPI_Datatype
, 
.I MPI_Comm
) are of type 
.I INTEGER
in Fortran.
.SH LOCATION
pcontrol.c
