.TH MPIO_Request_c2f 3 "6/8/2005" " " "MPI-2"
.SH NAME
MPIO_Request_c2f \-  Translates a C I/O-request handle to a  Fortran I/O-request handle 
.SH SYNOPSIS
.nf
#ifdef HAVE_MPI_GREQUEST
MPI_Fint MPIO_Request_c2f(MPIO_Request request)
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B request 
- C I/O-request handle (handle)
.PD 1

.SH RETURN VALUE
Fortran I/O-request handle (integer)
.SH LOCATION
ioreq_c2f.c
