.TH MPE_Fill_circle 4 "12/6/2001" " " "MPE"
.SH NAME
MPE_Fill_circle \-  Fills a circle 
.SH SYNOPSIS
.nf
#include "mpe.h" 
int MPE_Fill_circle( graph, centerx, centery, radius, color )
MPE_XGraph graph;
int centerx, centery, radius;
MPE_Color color;
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B graph 
- MPE graphics handle
.PD 1
.PD 0
.TP
.B centerx 
- horizontal center point of the circle
.PD 1
.PD 0
.TP
.B centery 
- vertical center point of the circle
.PD 1
.PD 0
.TP
.B radius 
- radius of the circle
.PD 1
.PD 0
.TP
.B color 
- color of the circle
.PD 1


.SH NOTES FOR FORTRAN INTERFACE 
The Fortran interface to this routine is different from its C
counterpart and it has an additional argument, ierr, at the end
of the argument list, i.e. the returned function value (the error
code) in C interface is returned as the additional argument in
Fortran interface.  The Fortran interface is invoked with the
CALL statement.

All MPI and MPE objects, MPI_Comm, MPE_XGraph and MPE_Color, are
of type INTEGER in Fortran.
.SH LOCATION
mpe_graphics.c
