.TH SLURMSTEPD "8" "September 2006" "slurmstepd 1.1" "Slurm components"
.SH "NAME"
slurmstepd \- The job step manager for SLURM.
.SH "SYNOPSIS"
\fBslurmstepd\fR
.SH "DESCRIPTION"
\fBslurmstepd\fR is a job step manager for SLURM. 
It is spawned by the \fBslurmd\fR daemon when a job step is launched 
and terminates when the job step does. 
It is responsible for managing input and output (stdin, stdout and stderr)
for the job step along with its accounting and signal processing. 
\fBslurmstepd\fR should not be initiated by users or system administrators.
.SH "COPYING"
Copyright (C) 2006 The Regents of the University of California.
Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
LLNL\-CODE\-402394.
.LP
This file is part of SLURM, a resource management program.
For details, see <https://computing.llnl.gov/linux/slurm/>.
.LP
SLURM is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 2 of the License, or (at your option)
any later version.
.LP
SLURM is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
details.
.SH "SEE ALSO"
\fBslurmd\fR(8)
