.TH SMAP "1" "January 2005" "smap 0.4" "Slurm components"

.SH "NAME"
smap \- graphically view information about SLURM jobs, partitions, and set 
configurations parameters.

.SH "SYNOPSIS"
\fBsmap\fR [\fIOPTIONS\fR...] 
.SH "DESCRIPTION"
\fBsmap\fR is used to graphically view job, partition and node information 
for a system running SLURM. 

.SH "OPTIONS"
.TP
\fB\-\-help\fR,
Print a message describing all \fBsmap\fR options.
.TP
\fB\-\-usage\fR
Print a brief message listing the \fBsmap\fR options.
.TP
\fB\-D <option>\fR, \fB\-\-display=<option>\fR
sets the display mode for smap. Showing revelant information about specific 
views and displaying a corresponding node chart. While in any 
display a user can switch by typing a different view letter.  This is true in
all modes except for 'configure mode' user can type 'quit' to exit just 
configure mode.  Typing 'exit' will end the configuration mode and exit smap.
Note that unallocated nodes are indicated by a '.' and DOWN or DRAINED 
nodes by a '#'.
\fB\-R <RACK_MIDPLANE_ID/XYZ>\fR, \fB\-\-resolve=<RACK_MIDPLANE_ID/XYZ>\fR
Returns the XYZ coords for a Rack/Midplane id or vice-versa.

To get the XYZ coord for a Rack/Midplane id input -R R101 where 10 is the rack
and 1 is the midplane.  

To get the Rack/Midplane id from a XYZ coord input -R 101 where X=1 Y=1 Z=1 with
no leading 'R'.  
.RS
.TP 15
.I "j"
Displays information about jobs running on system.
.TP 
.I "s"
Displays information about slurm partitions on the system
.TP
.I "b"
Displays information about BGL partitions on the system
.TP
.I "c"
Displays current node states and allows users to configure the system.
.RE
.TP
\fB\-h\fR, \fB\-\-noheader\fR
Do not print a header on the output.
.TP
\fB\-c\fR, \fB\-\-commandline\fR
Print output to the commandline, no curses.
.TP
\fB\-p\fR, \fB\-\-parse\fR
Used with -c commandline option. Don't format output send only single 
tab delimited output to stdout.
.TP
\fB\-i <seconds>\fR , \fB\-\-iterate=<seconds>\fR
Print the state on a periodic basis. 
Sleep for the indicated number of seconds between reports.
User can exit at anytime by typing 'q' or hitting the return key.
If user is in configure mode type 'exit' to exit program, 'quit' 
to exit configure mode.
.TP
\fB\-V\fR , \fB\-\-version\fR
Print version information and exit.

.SH "OUTPUT FIELD DESCRIPTIONS"
.TP
\fBAVAIL\fR
Partition state: \fBup\fR or \fBdown\fR.
.TP
\fBBGL_BLOCK\fR
BGL Block Name\fR.
.TP
\fBCONN\fR
Connection Type: \fBTORUS\fR or \fBMESH\fR.
.TP
\fBID\fR
Key to identify the nodes associated with this entity in the node chart.
.TP
\fBMODE\fR
Mode Type: \fBCOPROCESS\fR or \fBVIRTUAL\fR.
.TP
\fBNAME\fR
Name of the job.
.TP
\fBNODELIST\fR
Names of nodes associated with this configuration/partition.
.TP
\fBNODES\fR
Count of nodes with this particular configuration.
.TP
\fBPARTITION\fR
Name of a partition.  Note that the suffix "*" identifies the
default partition.
.TP
\fBST\fR
State of a job in compact form. Possible states include:
PD (pending), R (running), CG (completing),  CD  (completed), 
F (failed), TO (timeout), and NF (node failure). See 
\fBJOB STATE CODES\fR section below for more information.
.TP
\fBSTATE\fR
State of the nodes. Possible states include: down, unknown,
idle, allocated, drained, draining, completing and their
abbreviated forms: down, unk, idle, alloc, drain, drng, and
comp respectively.  Note that the suffix "*" identifies nodes
that are presently not responding.
See \fBNODE STATE CODES\fR section below for more information.
\fBTIMELIMIT\fR
Maximum time limit for any user job in
days:hours:minutes:seconds.  \fBinfinite\fR is used to identify
jobs or partitions without a job time limit.
.TP

.SH "TOPOGRAPHY INFORMATION"
.PP
The node chart is designed to indicate relative locations of 
the nodes. 
On most Linux clusters this will represent a one-dimensional 
array of nodes. Larger clusters will utilize multiple as needed 
with right side of one line being logically followed by the 
left side of the next line.
.PP
.nf
On Blue Gene systems, the node chart will indicate the three 
dimensional topography of the system.
The X dimension will increase from left to right on a given line.
The Y dimension will increase in planes from bottom to top.
The Z dimension will increase within a plane from the back 
line to the front line of a plane.
Note the example below:

ID JOBID PARTITION USER   NAME ST TIME NODES NODELIST
a  12345 batch    joseph tst1 R  43:12   64 bgl[000x333]
b  12346 debug    chris  sim3 R  12:34   16 bgl[420x533]
c  12350 debug    danny  job3 R   0:12    8 bgl[622x733]
d  12356 debug    dan    colu R  18:05   16 bgl[600x731]
e  12378 debug    joseph asx4 R   0:34    4 bgl[612x713]

   a a a a b b d d
  a a a a b b d d
 a a a a b b c c
a a a a b b c c

   a a a a b b d d
  a a a a b b d d
 a a a a b b c c
a a a a b b c c

   a a a a . . d d
  a a a a . . d d
 a a a a . . e e              Y
a a a a . . e e               |
                              |
   a a a a . . d d            0----X
  a a a a . . d d            /
 a a a a . . . .            /
a a a a . . . #            Z

.fi

.SH "CONFIGURATION INSTRUCTIONS"
.PP
For Admin use. From this screen one can create a configuration 
file that is used to partition and wire the system into usable
blocks.  

.TP
\fBOUTPUT\fR

.TP
.I "BGL_BLOCK" BGL Block Name.
.TP
.I "CONN"
Connection Type: \fBTORUS\fR or \fBMESH\fR.
.TP
.I "ID"
Key to identify the nodes associated with this entity in the node chart.
.TP
.I "MODE"
Mode Type: \fBCOPROCESS\fR or \fBVIRTUAL\fR.
	
.TP
\fBINPUT COMMANDS\fR
.TP
.I \fresolce <RACK_MIDPLANE_ID/XYZ>\fR
Returns the XYZ coords for a Rack/Midplane id or vice-versa.

To get the XYZ coord for a Rack/Midplane id input -R R101 where 10 is the rack
and 1 is the midplane.  

To get the Rack/Midplane id from a XYZ coord input -R 101 where X=1 Y=1 Z=1 with
no leading 'R'.  

.RS
.TP
.I \fBcreate <size> <options>\fR
Submit request for partition creation. The size may be specified either 
as a count of base partitions or specific dimensions in the X, Y and Z 
directions separated by "x", for example "2x3x4". A variety of options 
may be specified. Valid options are listed below. Note that the option
and their values are case insensitive (e.g. "MESH" and "mesh" are equivalent).

.RS
.TP 10
.I \fBConnection = MESH | TORUS\fR
Identify how the nodes should be connected in network. 
The default value is TORUS.
.TP
.I \fBMesh\fR
Equivalent to "Connection=Mesh".
.TP
.I \fBTorus\fR
Equivalent to "Connection=Torus".
.TP
.I \fBRotation = TRUE | FALSE\fR
Specifies that the geometry specified in the size parameter may 
be rotated in space (e.g. the Y and Z dimensions may be switched).
The default value is FALSE.
.TP
.I \fBRotate\fR
Equivalent to "Rotation=true".
.TP
.I \fBMode = COPROC | VIRTUAL\fR
Specify how the second processor on a c-node should be used. 
To use it for computation, specify VIRTUAL. 
To use it for communications, specify COPROC.
The default value is COPROC.
.TP
.I \fBCoproc\fR
Equivalent to "Mode=Coproc".
.TP
.I \fBVirtual\fR
Equivalent to "Mode=Virtual".
.TP
.I \fBElongation = TRUE | FALSE\fR
If TRUE, permit the geometry specified in the size parameter to be altered as 
needed to fit available resources. 
For example, an allocation of "4x2x1" might be used to satisfy a size specification 
of "2x2x2". 
The default value is FALSE.
.TP
.I \fBElongate\fR
Equivalent to "Elongation=true".
.RE

.TP
.I \fBcopy <id> <count>\fR
Submit request for partition to be copied. 
You may copy a specific partition by specifying its id, by default the 
last configured partition is copied. 
You may also specify a number of copies to be made. 
By default, one copy is made.

.TP
.I \fBdelete <id>\fR
Delete the specified block or (default) the last partition created. 

.TP
.I \fBdown <node_range>\fR
Down a specific node or range of nodes. 
i.e. 000, 000-111 [000x111]

.TP
.I \fBsave <file_name>\fR
Save the current configuration to a file. 
If no file_name is specified, the configuration is written to a 
file named "bluegene.conf" in the current working directory.

.TP
.I \fBclear\fR
Clear all partitions created.

.SH "NODE STATE CODES"
.PP
Node state codes are shortened as required for the field size.
If the node state code is followed by "*", this indicates the
node is presently not responding and will not be allocated
any new work.  If the node remains non-responsive, it will
be placed in the \fBDOWN\fR state (except in the case of
\fBDRAINED\fR, \fBDRAINING\fR, or \fBCOMPLETING\fR nodes).
.TP 12
ALLOCATED
The node has been allocated to one or more jobs.
.TP
COMPLETING
One or more jobs have been allocated this node and are in
the process of COMPLETING. This node state will be removed when
all of the job's processes have terminated and the SLURM
epilog program (if any) has terminated. See the \fBEpilog\fR
parameter description in the \fBslurm.conf\fR man page for
more information.
.TP
DOWN
The node is unavailable for use. SLURM can automatically
place nodes in this state if some failure occurs. System
administrators may also explicitly place nodes in this state. If
a node resumes normal operation, SLURM can automatically
return it to service. See the \fBReturnToService\fR
and \fBSlurmdTimeout\fR parameter descriptions in the
\fBslurm.conf\fR(5) man page for more information.
.TP
DRAINED
The node is unavailable for use per system administrator
request.  See the \fBupdate node\fR command in the
\fBscontrol\fR(1) man page or the \fBslurm.conf\fR(5) man page
for more information.
.TP
DRAINING
The node is currently executing a job, but will not be allocated
to additional jobs. The node state will be changed to state
\fBDRAINED\fR when the last job on it completes. Nodes enter
this state per system administrator request. See the \fBupdate
node\fR command in the \fBscontrol\fR(1) man page or the
\fBslurm.conf\fR(5) man page for more information.
.TP
IDLE
The node is not allocated to any jobs and is available for use.
.TP
UNKNOWN
The SLURM controller has just started and the node's state
has not yet been determined.

.SH "JOB STATE CODES"
Jobs typically pass through several states in the course of their
execution.
The typical states are PENDING, RUNNING, COMPLETING, and COMPLETED.
An explanation of each state follows.
.TP 20
CA  CANCELLED
Job was explicitly cancelled by the user or system administrator.
The job may or may not have been initiated.
.TP
CD  COMPLETED
Job has terminated all processes on all nodes.
.TP
CG  COMPLETING
Job is in the process of completing. Some processes on some nodes may still be active.
.TP
F   FAILED
Job terminated with non-zero exit code or other failure condition.
.TP
NF  NODE_FAIL
Job terminated due to failure of one or more allocated nodes.
.TP
PD  PENDING
Job is awaiting resource allocation.
.TP
R   RUNNING
Job currently has an allocation.
.TP
TO  TIMEOUT
Job terminated upon reaching its time limit.

.SH "COPYING"
Copyright (C) 2004 The Regents of the University of California.
Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
UCRL-CODE-2002-040.
.LP
This file is part of SLURM, a resource management program.
For details, see <http://www.llnl.gov/linux/slurm/>.
.LP
SLURM is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 2 of the License, or (at your option)
any later version.
.LP
SLURM is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
details.
.SH "SEE ALSO"
\fBscontrol\fR(1), fBsinfo\fR(1), \fBsqueue\fR(1), 
\fBslurm_load_ctl_conf\fR(3), \fBslurm_load_jobs\fR(3), \fBslurm_load_node\fR(3), 
\fBslurm_load_partitions\fR(3), 
\fBslurm_reconfigure\fR(3), \fBslurm_shutdown\fR(3), 
\fBslurm_update_job\fR(3), \fBslurm_update_node\fR(3), 
\fBslurm_update_partition\fR(3),
\fBslurm.conf\fR(5)
