.TH SLURMD "8" "October 2002" "slurmd 0.1" "Slurm components"
.SH "NAME"
slurmd \- The compute node daemon of Slurm.
.SH "SYNOPSIS"
\fBslurmd\fR [\fIOPTIONS\fR...]
.SH "DESCRIPTION"
\fBslurmld\fR is the compute node daemon of Slurm. It monitors all tasks 
running on the compute node , accepts work (tasks), launches tasks, and kills 
running tasks upon request.
.TP
OPTIONS
.TP
\fB-c\fR
Clear system locks as needed. This may be required if \fBslurmd\fR terminated 
abnormally.
.TP
\fB-D\fR
Run slurmd in the foreground. Error and debug messages will be copied to stderr.
.TP
\fB-v\fR
Verbose operation. Multiple -v's increase verbosity.
.TP
\fB-h\fR
Help; print a brief summary of command options.
.TP
\fB-f <file>\fR
Read configuration from the specified file.
.TP
\fB-L <file>\fR
Write log messages to the specified file.
.TP
.SH "NOTES"
It may be useful to experiment with different \fBslurmd\fR specific 
configuration parameters using a distinct configuration file. However, 
this special configuration file will not be recognized by \fBslurmctld\fR 
or the Slurm programs. If you desire changing communication ports, 
the location of the temporary file system, or other parameters used 
by other Slurm components, change the common configuration file.
.SH "COPYING"
Copyright (C) 2002 The Regents of the University of California.
Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
UCRL-CODE-2002-040.
.LP
This file is part of SLURM, a resource management program.
For details, see <http://www.llnl.gov/linux/slurm/>.
.LP
SLURM is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 2 of the License, or (at your option)
any later version.
.LP
SLURM is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
details.
.SH "FILES"
.LP
/etc/slurm.conf
.SH "SEE ALSO"
\fBslurm.conf\fR(5), \fBslurmctld\fR(8)
