#!/usr/bin/perl
open OUT, ">test.out" ;
close OUT ;

for ( $i=0 ; $i < 30 ;  $i++ )
{
open OUT, ">test.out" ;
print OUT `date`;
print "stdout -- $i \n" ;
print OUT "stdout -- $i \n" ;
print "$i stdout 1 TESTING\n" ;
print "$i stdout 2 TESTING\n" ;
print "$i stdout 3 TESTING\n" ;
print "$i stdout 4 TESTING\n" ;
print STDERR "$i stderr 1 ETESTING\n" ;
print STDERR "$i stderr 2 ETESTING\n" ;
print STDERR "$i stderr 3 ETESTING\n" ;
print STDERR "$i stderr 4 ETESTING\n" ;
print OUT "OTESTING\n" ;
print OUT "OTESTING\n" ;
print OUT "OTESTING\n" ;
print OUT "OTESTING\n" ;
close OUT ;
open OUT, ">>test.out" ;
print "$i stdout 5 TESTING\n" ;
print "$i stdout 6 TESTING\n" ;
print "$i stdout 7 TESTING\n" ;
print "$i stdout 8 TESTING\n" ;
print STDERR "$i stderr 5 ETESTING\n" ;
print STDERR "$i stderr 6 ETESTING\n" ;
print STDERR "$i stderr 7 ETESTING\n" ;
print STDERR "$i stderr 8 ETESTING\n" ;
print OUT "ONOTESTING\n" ;
print OUT "ONOTESTING\n" ;
print OUT "ONOTESTING\n" ;
print OUT "ONOTESTING\n" ;
close OUT ;
}
