/* This file autogenerated by src/common/Makefile */
char *default_plugin_path = "/home/jette/slurm.way/lib/slurm";
char *default_slurm_config_file = "/home/jette/slurm.way/etc/slurm.conf";
char *default_plugstack = "/home/jette/slurm.way/etc/plugstack.conf";
