#! /bin/sh
# 
# This script updates the ADIs that are derived from the Chameleon version
(cd ch_cmmd ; makecmmd )
(cd ch_eui ; makeeui )
(cd ch_nc ; maken3 )
(cd ch_nx ; makenx )
(cd ch_p4 ; makep4 )
(cd ch_meiko ; makemeiko )
(cd ch_pvm3_3 ; makepvm3_3 )
(cd ch_tcp ; maketcp )
(cd ch_shmem ; makeshmem )
(cd ch_spp ; makespp )
#(cd ch_shsgi ; makeshsgi )
#(cd ch_sgisproc ; makesgisproc )
(cd ch_dummy ; makedummy )
