#!/bin/csh
/u5/rbutler/p4/p4-1.4dqs/messages/systest1 \
    -p4dbg 11 -p4rdbg 11 \
    -execer_id DQS \
    -master_host sinkhole \
    -my_hostname sinkhole \
    -my_nodenum 0 \
    -my_numprocs 1 \
    -total_numnodes 3 \
    -job_id  5555  \
    -remote_info  \
	sinkhole 1 1 /slave_full_pathname  \
	sinkhole 2 1 /slave_full_pathname
