.TH SACCTMGR "1" "September 2008" "sacctmgr 1.3" "Slurm components"

.SH "NAME"
sacctmgr \- Used to view and modify Slurm account information.

.SH "SYNOPSIS"
\fBsacctmgr\fR [\fIOPTIONS\fR...] [\fICOMMAND\fR...]

.SH "DESCRIPTION"
\fBsacctmgr\fR is used to view or modify Slurm account information.
The account information is maintained within a database with the interface 
being provided by \fBslurmdbd\fR (Slurm Database daemon).
This database can serve as a central storehouse of user and 
computer information for multiple computers at a single site.
Slurm account information is recorded based upon four parameters
that form what is refered to as an \fIassociation\fR. 
These parameters are \fIuser\fR, \fIcluster\fR, \fIpartition\fR, and 
\fIaccount\fR. \fIuser\fR is the login name.
\fIcluster\fR is the name of a Slurm managed cluster as specified by 
the \fIClusterName\fR parameter in the \fIslurm.conf\fR configuration file. 
\fIpartition\fR is the name of a Slurm partition on that cluster.
\fIaccount\fR is the bank account for a job.
The intended mode of operation is to initiate the \fBsacctmgr\fR command, 
add, delete, modify, and/or list \fIassociation\fR records then 
commit the changes and exit.

.SH "OPTIONS"
.TP
\fB\-h\fR, \fB\-\-help\fR
Print a help message describing the usage of \fBssacctmgr\fR.
This is equivalent to the \fBhelp\fR command.

.TP
\fB\-i\fR, \fB\-\-immediate\fR
commit changes immediately.

.TP
\fB\-n\fR, \fB\-\-no_header\fR
No header will be added to the beginning of the output.

.TP
\fB\-o\fR, \fB\-\-oneliner\fR
Report output one record per line.
This is equivalent to the \fBoneliner\fR command.

.TP
\fB\-p\fR, \fB\-\-parsable\fR
Output will be '|' delimited with a '|' at the end.

.TP
\fB\-P\fR, \fB\-\-parsable2\fR
Output will be '|' delimited without a '|' at the end.

.TP
\fB\-q\fR, \fB\-\-quiet\fR
Print no messages other than error messages.
This is equivalent to the \fBquiet\fR command.

.TP
\fB\-r\fR, \fB\-\-readonly\fR
Makes it so the running sacctmgr can not modify accounting information.
This is equivalent to the \fBreadonly\fR command.

.TP
\fB\-s\fR, \fB\-\-associations\fR
Use with show or list to display associations with the entity.
This is equivalent to the \fBassociations\fR command.

.TP
\fB\-v\fR, \fB\-\-verbose\fR
Enable detailed logging. 
This is equivalent to the \fBverbose\fR command.

.TP
\fB\-V\fR , \fB\-\-version\fR
Display version number.
This is equivalent to the \fBversion\fR command.

.SH "COMMANDS"

.TP
\fBadd\fR <\fIENTITY\fR> <\fISPECS\fR>
Add an entity.
Identical to the \fBcreate\fR command.

.TP
\fBassociations\fR
Use with show or list to display associations with the entity.

.TP
\fBcreate\fR <\fIENTITY\fR> <\fISPECS\fR>
Add an entity.
Identical to the \fBadd\fR command.

.TP
\fBdelete\fR <\fIENTITY\fR> with <\fISPECS\fR>
Delete the specified entities.

.TP
\fBdump\fR <\fIENTITY\fR> with <\fIFILENAME\fR>
Dump cluster data to the specified file.

.TP
\fBexit\fP
Terminate sacctmgr.
Identical to the \fBquit\fR command.

.TP
\fBhelp\fP
Display a description of sacctmgr options and commands.

.TP
\fBlist\fR <\fIENTITY\fR> [with <\fISPECS\fR>]
Display information about the specified entities.
By default, all entities are displayed.
Identical to the \fBshow\fR command.

.TP
\fBload\fR <\fIFILENAME\fR>
Load cluster data to the specified file.

.TP
\fBmodify\fR <\fIENTITY\fR> \fbwith\fR <\fISPECS\fR> \fbset\fR <\fISPECS\fR>
Modify an entity.

.TP
\fBoneliner\fP
Output one record per line.

.TP
\fBquiet\fP
Print no messages other than error messages.

.TP
\fBquit\fP
Terminate the execution of sacctmgr.
Identical to the \fBexit\fR command.

.TP
\fBshow\fR <\fIENTITY\fR> [with <\fISPECS\fR>]
Display information about the specified entities.
By default, all entities are displayed.
Identical to the \fBlist\fR command.

.TP
\fBverbose\fP
Enable detailed logging. 
This includes time\-stamps on data structures, record counts, etc.
This is an independent command with no options meant for use in interactive mode.

.TP
\fBversion\fP
Display the version number of sacctmgr.

.TP
\fB!!\fP
Repeat the last command.

.TP
\fBENTITIES\fR

.TP
\fIaccount\fP
A bank account, typically specified at job submit time using the 
\fI--account=\fR option.
These may be arranged in a hierarchical fashion, for example
accounts \fIchemistry\fR and \fIphysics\fR may be children of
the account \fIscience\fR. 
The hierarchy may have an arbitrary depth.

.TP
\fIassociation\fP
The entity used to group information consisting of four parameters:
\fIaccount\fR, \fIcluster\fR, \fIpartition (optional)\fR, and \fIuser\fR.

.TP
\fIcluster\fP
The \fIClusterName\fR parameter in the \fIslurm.conf\fR configuration
file, used to differentiate accounts from on different machines. 

.TP
\fIcoordinator\fR
A special priviaged user usually an account manager or such that can
add users or sub accounts to the account they are coordinator over.
This should be a trusted person since they can change limits on
account and user associations inside their realm.
 
.TP
\fIqos\fR
Quality of Service (For use with MOAB only).

.TP
\fItransaction\fR
List of transactions that have occured during a given time period.

.TP
\fIuser\fR
The login name.

.TP
\fBSPECIFICATIONS FOR ACCOUNTS\fR
.TP
\fICluster\fP=<cluster>
Specific cluster to add account to.  Default is all in system.
.TP
\fIDescription\fP=<description>
An arbitrary string describing an account.
.TP
\fIFairshare\fP=<fairshare>
Number used in conjunction with other accounts to determine job priority.
To clear a previously set value use the modify command with a new value of \-1.
.TP
\fIMaxCPUSecs\fP=<max cpu seconds> 
Maximum number of cpu seconds each job is able to use in this account.
This is overridden if set directly on a user. 
Default is the cluster's limit.
To clear a previously set value use the modify command with a new value of \-1.
.TP
\fIMaxJobs\fP=<max jobs>
Maximum number of jobs each user is allowed to run at one time in this account.
This is overridden if set directly on a user. 
Default is the cluster's limit.
To clear a previously set value use the modify command with a new value of \-1.
.TP
\fIMaxNodes\fP=<max nodes>
Maximum number of nodes each job is able to use in this account.
This is overridden if set directly on a user. 
Default is the cluster's limit.
To clear a previously set value use the modify command with a new value of \-1.
This is a c\-node limit on BlueGene systems.
.TP
\fIMaxWall\fP=<max wall>
Maximum wall clock time each job is able to use in this account.
This is overridden if set directly on a user. 
Default is the cluster's limit.
<max wall> format is <min> or <min>:<sec> or <hr>:<min>:<sec> or 
<days>\-<hr>:<min>:<sec> or <days>\-<hr>.
The value is recorded in minutes with rounding as needed.
To clear a previously set value use the modify command with a new value of \-1.
.TP
\fIName\fP=<name>
The name of a bank account.
.TP
\fIOrganization\fP=<org>
Organization to which the account belongs.
.TP
\fIParent\fP=<parent>
Parent account of this account. Default is no parent, a top level account.
.TP
\fIQosLevel\fP=<qos>
Quality of Service jobs are to run at for this account.  Now consisting
of Normal, Standby, Expedite, and Exempt.
This is overridden if set directly on a user. 

.TP
\fBSPECIFICATIONS FOR CLUSTERS\fR
.TP
\fIFairshare\fP=<fairshare>
Number used in conjunction with other accounts to determine job priority.
To clear a previously set value use the modify command with a new value of \-1.
.TP
\fIName\fP=<name>
The name of a cluster.
This should be equal to the \fIClusterName\fR parameter in the \fIslurm.conf\fR 
configuration file for some Slurm-managed cluster. 
.TP
\fIMaxCPUSecs\fP=<max cpu seconds> 
Maximum number of cpu seconds each job is able to use in this account.
This is overridden if set directly on an account or user. 
Default is no limit.
To clear a previously set value use the modify command with a new value of \-1.
\fIMaxJobs\fP=<max jobs>
Maximum number of jobs each user is allowed to run at one time in this account.
This is overridden if set directly on an account or user. 
Default is no limit.
To clear a previously set value use the modify command with a new value of \-1.
.TP
\fIMaxNodes\fP=<max nodes>
Maximum number of nodes each job is able to use in this account.
This is overridden if set directly on an account or user. 
Default is no limit.
To clear a previously set value use the modify command with a new value of \-1.
This is a c\-node limit on BlueGene systems.
.TP
\fIMaxWall\fP=<max wall>
Maximum wall clock time each job is able to use in this account.
This is overridden if set directly on an account or user. 
Default is no limit.
<max wall> format is <min> or <min>:<sec> or <hr>:<min>:<sec> or 
<days>\-<hr>:<min>:<sec> or <days>\-<hr>.
The value is recorded in minutes with rounding as needed.
To clear a previously set value use the modify command with a new value of \-1.
.TP
\fIQosLevel\fP=<qos>
Quality of Service jobs are to run at for this account.  Now consisting
of Normal, Standby, Expedite, and Exempt.
This is overridden if set directly on an account or user. 

.TP
\fBSPECIFICATIONS FOR COORDINATOR\fR
.TP
\fIAccountsfP=<comma separated list of account names>
Account name to add this user as a coordinator to.
.TP
\fINames\fP=<comma separated list of user names>
Names of coordinators.

.TP
\fBSPECIFICATIONS FOR QOS\fR
.TP
\fIDescription\fP=<description>
An arbitrary string describing an account.
.TP
\fINames\fP=<qos>
Names of qos.

.TP
\fBSPECIFICATIONS FOR USERS\fR
.TP
\fIAccount\fP=<account>
Account name to add this user to.
.TP
\fIAdminLevel\fP=<level>
Admin level of user.  Valid levels are None, Operator, and Admin.
.TP
\fICluster\fP=<cluster>
Specific cluster to add user to the account on.  Default is all in system.
.TP
\fIDefaultAccount\fP=<account>
Identify the default bank account name to be used for a job if none is 
specified at submission time.
.TP
\fIFairshare\fP=<fairshare>
Number used in conjunction with other users in the same account to
determine job priority.
To clear a previously set value use the modify command with a new value of \-1.
.TP
\fIName\fP=<name>
Name of user.
.TP
\fIQosLevel\fP=<qos>
The Quality of Service jobs are to run at for this user using the
account specified.  Now consisting of Normal, Standby, Expedite, and Exempt.
.TP
\fIMaxCPUSecs\fP=<max cpu seconds> 
Maximum number of cpu seconds this user can use in each job using the
account specified.
To clear a previously set value use the modify command with a new value of \-1.
.TP
\fIMaxJobs\fP=<max jobs>
Maximum number of jobs this user can run at a given time using the
account specified.
This is overridden if set directly on a user. 
Default is the account's limit.
To clear a previously set value use the modify command with a new value of \-1.
.TP
\fIMaxNodes\fP=<max nodes>
Maximum number of nodes this user can allocate in each job using the
account specified. 
Default is the account's limit.
This is a c\-node limit on BlueGene systems.
.TP
\fIMaxWall\fP=<max wall>
Maximum wall clock time this user can use in each job using the
account specified.
Default is the account's limit.
<max wall> format is <min> or <min>:<sec> or <hr>:<min>:<sec> or 
<days>\-<hr>:<min>:<sec> or <days>\-<hr>.
The is recorded in minutes with rounding as needed.
To clear a previously set value use the modify command with a new value of \-1.


.SH "FLAT FILE DUMP AND LOAD"
sacctmgr has the capability to load and dump Slurm account data to and
from a file. Each file contains Slurm account data for one
cluster. Loading a file will modify the database. Blank lines in the
file must begin with the # character. Each line of information will
begin with one of the four titles; Cluster, Parent, Account or
User. Following the title is a space, dash, space, entity value, then specifications. Specifications are colon separated with string values enclosed in
single quotes. An example of the form is:

Cluster\ \-\ tux
.br
Parent\ \-\ root
.br
Account\ \-\ physics:Description='physics\ account':Organization='science':QOS='normal':Fairshare=10:MaxCPUSecs=700:MaxJobs=3:MaxNodes=9:MaxWallDurationPerJob=3600
.br
User\ \-\ adam:DefaultAccount='physics':QOS='normal':Fairshare=4:MaxCPUSecs=400:MaxJobs=2:MaxNodes=4:MaxWallDurationPerJob=3600:AdminLevel='Administrator':Coordinator='physics'


.SH "EXAMPLES"
.eo
.br
> sacctmgr create cluster=tux
.br
> sacctmgr create account name=science fairshare=50
.br
> sacctmgr create account name=chemistry parent=science fairshare=30
.br
> sacctmgr create account name=physics parent=science fairshare=20
.br
> sacctmgr create user name=adam cluster=tux account=physics \
.br 
  fairshare=10
.br
> sacctmgr modify user with name=adam cluster=tux account=physics \
.br
  set maxjobs=2 maxtime=30:00
.br
> sacctmgr dump cluster=tux tux_data_file
.br
> sacctmgr load tux_data_file
.br
.ec

.SH "COPYING"
Copyright (C) 2008 Lawrence Livermore National Security.
Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
LLNL\-CODE\-402394.
.LP
This file is part of SLURM, a resource management program.
For details, see <https://computing.llnl.gov/linux/slurm/>.
.LP
SLURM is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 2 of the License, or (at your option)
any later version.
.LP
SLURM is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
details.

.SH "SEE ALSO"
\fBslurm.conf\fR(5)
\fBslurmdbd\fR(8)
