#!/bin/csh
/margit/c/users/rbutler/p4-1.4dqs/messages/systest1 \
    -p4dbg 11 -p4rdbg 11 \
    -execer_id DQS \
    -master_host dirac \
    -my_hostname dirac \
    -my_nodenum 0 \
    -my_numprocs 1 \
    -total_numnodes 3 \
    -job_id  5555  \
    -remote_info  \
	ibm11 1 1 /slave_full_pathname  \
	ibm12 2 1 /slave_full_pathname
