.TH MPI_Wtick 3 "8/20/2004" " " "MPI"
.SH NAME
MPI_Wtick \-  Returns the resolution of MPI_Wtime 
.SH SYNOPSIS
.nf
#include "mpi.h"
double MPI_Wtick()
.fi
.SH RETURN VALUE
Time in seconds of the resolution of MPI_Wtime .

.SH NOTES FOR FORTRAN
This is a function, declared as 
.I DOUBLE PRECISION MPI_WTICK()
in Fortran.

.SH LOCATION
wtick.c
