.TH MPI_Type_create_subarray 3 "11/14/2001" " " "MPI-2"
.SH NAME
MPI_Type_create_subarray \-  Creates a datatype describing a subarray of a multidimensional array 
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Type_create_subarray(
        int ndims, 
        int *array_of_sizes, 
        int *array_of_subsizes, 
        int *array_of_starts, 
        int order, 
        MPI_Datatype oldtype, 
        MPI_Datatype *newtype)
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B ndims 
- number of array dimensions (positive integer)
.PD 1
.PD 0
.TP
.B array_of_sizes 
- number of elements of type oldtype in each dimension of the full array (array of positive integers)
.PD 1
.PD 0
.TP
.B array_of_subsizes 
- number of elements of type oldtype in each dimension of the subarray (array of positive integers)
.PD 1
.PD 0
.TP
.B array_of_starts 
- starting coordinates of the subarray in each dimension (array of nonnegative integers)
.PD 1
.PD 0
.TP
.B order 
- array storage order flag (state)
.PD 1
.PD 0
.TP
.B oldtype 
- old datatype (handle)
.PD 1

.SH OUTPUT PARAMETERS
.PD 0
.TP
.B newtype 
- new datatype (handle)
.PD 1

.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 
.I MPI_WTIME
and 
.I MPI_WTICK
) have
an additional argument 
.I ierr
at the end of the argument list.  
.I ierr
is an integer and has the same meaning as the return value of the routine
in C.  In Fortran, MPI routines are subroutines, and are invoked with the
.I call
statement.

All MPI objects (e.g., 
.I MPI_Datatype
, 
.I MPI_Comm
) are of type 
.I INTEGER
in Fortran.
.SH LOCATION
subarray.c
