.TH MPI_Finalize 3 "4/9/2002" " " "MPI"
.SH NAME
MPI_Finalize \-  Terminates MPI execution environment 
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Finalize()
.fi
.SH NOTES
All processes must call this routine before exiting.  The number of
processes running 
.B after
this routine is called is undefined;
it is best not to perform much more than a 
.I return rc
after calling
.I MPI_Finalize
\&.


.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 
.I MPI_WTIME
and 
.I MPI_WTICK
) have
an additional argument 
.I ierr
at the end of the argument list.  
.I ierr
is an integer and has the same meaning as the return value of the routine
in C.  In Fortran, MPI routines are subroutines, and are invoked with the
.I call
statement.

All MPI objects (e.g., 
.I MPI_Datatype
, 
.I MPI_Comm
) are of type 
.I INTEGER
in Fortran.
.SH LOCATION
finalize.c
