#
# Config for topology-test. The node count is deliberately large so the test
# can catch node selection costs that only show up at scale.
#
ClusterName=test
SlurmdUser=root
SlurmctldHost=localhost
SlurmctldPort=6815
SlurmdPort=6820
#DebugFlags=Backfill,SelectType
PluginDir=../../../src/plugins/select/cons_tres/.libs/:../../../src/plugins/topology/flat/.libs/:../../../src/plugins/hash/k12/.libs/:../../../src/plugins/tls/none/.libs/:../../../src/plugins/cred/munge/.libs/:../../../src/plugins/certgen/script/.libs/

AuthType=""

SelectType=select/cons_tres
SelectTypeParameters=CR_Core
TopologyPlugin=topology/flat

NodeName=node[00001-16384] NodeAddr=localhost RealMemory=2000 CoresPerSocket=4
