.TH MPE_Describe_event 4 "11/5/2003" " " "MPE"
.SH NAME
MPE_Describe_event \-  Create log record describing an event type 
.SH SYNOPSIS
.nf
int MPE_Describe_event( event, name )
int event;
char *name;
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B event 
- Event number
.PD 1
.PD 0
.TP
.B name  
- String describing the event. 
.PD 1

.SH SEE ALSO
MPE_Log_get_event_number 
.br
.SH LOCATION
mpe_log.c
