.TH MPE_Initialized_logging 4 "11/5/2003" " " "MPE"
.SH NAME
MPE_Initialized_logging \-  Indicate whether MPE_Init_log or MPE_Finish_log have been called. 
.SH SYNOPSIS
.nf
int MPE_Initialized_logging ()
.fi
.SH RETURNS
0 if MPE_Init_log has not been called, 1 if MPE_Init_log has been called
but MPE_Finish_log has not been called, and 2 otherwise.
.SH LOCATION
mpe_log.c
