#!/usr/bin/perl

open OUT, ">test.out" ;
print OUT `date`;
print "TESTING\n" ;
print "TESTING\n" ;
print "TESTING\n" ;
print "TESTING\n" ;
print OUT "TESTING\n" ;
print OUT "TESTING\n" ;
print OUT "TESTING\n" ;
print OUT "TESTING\n" ;
print OUT "TESTING\n" ;
print OUT "TESTING\n" ;
close OUT ;
sleep ( 3 ) ;
open OUT, ">>test.out" ;
print "NOTESTING\n" ;
print "NOTESTING\n" ;
print "NOTESTING\n" ;
print "NOTESTING\n" ;
print OUT "NOTESTING\n" ;
print OUT "NOTESTING\n" ;
