#!/usr/bin/perl

while(1)
{
open OUT, ">test.out" ;
print OUT `date`;
print "TESTING\n" ;
print "TESTING\n" ;
print "TESTING\n" ;
print "TESTING\n" ;
print STDERR "ETESTING\n" ;
print STDERR "ETESTING\n" ;
print STDERR "ETESTING\n" ;
print STDERR "ETESTING\n" ;
print OUT "OTESTING\n" ;
print OUT "OTESTING\n" ;
print OUT "OTESTING\n" ;
print OUT "OTESTING\n" ;
close OUT ;
open OUT, ">>test.out" ;
print "NOTESTING\n" ;
print "NOTESTING\n" ;
print "NOTESTING\n" ;
print "NOTESTING\n" ;
print STDERR "ENOTESTING\n" ;
print STDERR "ENOTESTING\n" ;
print STDERR "ENOTESTING\n" ;
print STDERR "ENOTESTING\n" ;
print OUT "ONOTESTING\n" ;
print OUT "ONOTESTING\n" ;
print OUT "ONOTESTING\n" ;
print OUT "ONOTESTING\n" ;
close OUT ;
}
