#!/usr/bin/perl
open OUT, ">test.out" ;
close OUT ;

for ( $i=0 ; $i < 10 ;  $i++ )
{
open OUT, ">test.out" ;
print OUT `date`;
print "stdout -- $i \n" ;
print OUT "stdout -- $i \n" ;
print "stdout 1 TESTING\n" ;
print "stdout 2 TESTING\n" ;
print "stdout 3 TESTING\n" ;
print "stdout 4 TESTING\n" ;
print STDERR "stderr 1 ETESTING\n" ;
print STDERR "stderr 2 ETESTING\n" ;
print STDERR "stderr 3 ETESTING\n" ;
print STDERR "stderr 4 ETESTING\n" ;
print OUT "OTESTING\n" ;
print OUT "OTESTING\n" ;
print OUT "OTESTING\n" ;
print OUT "OTESTING\n" ;
close OUT ;
open OUT, ">>test.out" ;
print "stdout 5 TESTING\n" ;
print "stdout 6 TESTING\n" ;
print "stdout 7 TESTING\n" ;
print "stdout 8 TESTING\n" ;
print STDERR "stderr 5 ETESTING\n" ;
print STDERR "stderr 6 ETESTING\n" ;
print STDERR "stderr 7 ETESTING\n" ;
print STDERR "stderr 8 ETESTING\n" ;
print OUT "ONOTESTING\n" ;
print OUT "ONOTESTING\n" ;
print OUT "ONOTESTING\n" ;
print OUT "ONOTESTING\n" ;
close OUT ;
}
