.TH MPI_Address 3 "11/14/2001" " " "MPI"
.SH NAME
MPI_Address \-  Gets the address of a location in memory   
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Address( void *location, MPI_Aint *address)
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B location 
- location in caller memory (choice) 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B address 
- address of location (integer) 
.PD 1

.SH NOTE
This routine is provided for both the Fortran and C programmers.
On many systems, the address returned by this routine will be the same
as produced by the C 
.I &
operator, but this is not required in C and
may not be true of systems with word- rather than byte-oriented
instructions or systems with segmented address spaces.

.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 
.I MPI_WTIME
and 
.I MPI_WTICK
) have
an additional argument 
.I ierr
at the end of the argument list.  
.I ierr
is an integer and has the same meaning as the return value of the routine
in C.  In Fortran, MPI routines are subroutines, and are invoked with the
.I call
statement.

All MPI objects (e.g., 
.I MPI_Datatype
, 
.I MPI_Comm
) are of type 
.I INTEGER
in Fortran.
.SH LOCATION
address.c
