.TH MPI_Status_c2f 3 "8/30/1999" " " "MPI-2"
.SH NAME
MPI_Status_c2f \-  Convert a C status to a Fortran status 
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Status_c2f( MPI_Status *c_status, MPI_Fint *f_status )
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B c_status 
- Status value in C (Status)
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B f_status 
- Status value in Fortran (Integer)
.PD 1
.SH ERRORS

All MPI routines (except 
.I MPI_Wtime
and 
.I MPI_Wtick
) return an error value;
C routines as the value of the function and Fortran routines in the last
argument.  Before the value is returned, the current MPI error handler is
called.  By default, this error handler aborts the MPI job.  The error handler
may be changed with 
.I MPI_Errhandler_set
; the predefined error handler
.I MPI_ERRORS_RETURN
may be used to cause error values to be returned.
Note that MPI does 
.B not
guarentee that an MPI program can continue past
an error.

.PD 0
.TP
.B MPI_SUCCESS 
- No error; MPI routine completed successfully.
.PD 1
.PD 0
.TP
.B MPI_ERR_ARG 
- Invalid argument.  Some argument is invalid and is not
identified by a specific error class (e.g., 
.I MPI_ERR_RANK
).
.PD 1
.SH LOCATION
statusc2f.c
