.TH MPI_Info_create 3 "11/14/2001" " " "MPI-2"
.SH NAME
MPI_Info_create \-  Creates a new info object 
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Info_create(MPI_Info *info)
.fi
.SH OUTPUT PARAMETERS
.PD 0
.TP
.B info 
- info object (handle)
.PD 1

.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 
.I MPI_WTIME
and 
.I MPI_WTICK
) have
an additional argument 
.I ierr
at the end of the argument list.  
.I ierr
is an integer and has the same meaning as the return value of the routine
in C.  In Fortran, MPI routines are subroutines, and are invoked with the
.I call
statement.

All MPI objects (e.g., 
.I MPI_Datatype
, 
.I MPI_Comm
) are of type 
.I INTEGER
in Fortran.
.SH LOCATION
info_create.c
