.TH MPI_Dims_create 3 "4/24/2002" " " "MPI"
.SH NAME
MPI_Dims_create \-  Creates a division of processors in a cartesian grid 
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Dims_create(
        int nnodes, 
        int ndims, 
        int *dims)
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B nnodes 
- number of nodes in a grid (integer) 
.PD 1
.PD 0
.TP
.B ndims 
- number of cartesian dimensions (integer) 
.PD 1

.SH IN/OUT PARAMETER
.PD 0
.TP
.B dims 
- integer array of size  
.I ndims
specifying the number of nodes in each 
dimension  
.PD 1

.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 
.I MPI_WTIME
and 
.I MPI_WTICK
) have
an additional argument 
.I ierr
at the end of the argument list.  
.I ierr
is an integer and has the same meaning as the return value of the routine
in C.  In Fortran, MPI routines are subroutines, and are invoked with the
.I call
statement.

All MPI objects (e.g., 
.I MPI_Datatype
, 
.I MPI_Comm
) are of type 
.I INTEGER
in Fortran.
.SH LOCATION
dims_create.c
