.TH "gres.conf" "5" "July 2010" "gres.conf 2.2" "Slurm configuration file"
.SH "NAME"
gres.conf \- Slurm configuration file for generic resource management.

.SH "DESCRIPTION"
\fB/etc/gres.conf\fP is an ASCII file which describes the configuration
of generic resources on each compute node. Each node must contain a
gres.conf file if generic resources are to be scheduled by SLURM.
The file location can be modified at system build time using the
DEFAULT_SLURM_CONF parameter. The file will always be located in the
same directory as the \fBslurm.conf\fP file.
.LP
Parameter names are case insensitive.
Any text following a "#" in the configuration file is treated
as a comment through the end of that line.
The size of each line in the file is limited to 1024 characters.
Changes to the configuration file take effect upon restart of
SLURM daemons, daemon receipt of the SIGHUP signal, or execution
of the command "scontrol reconfigure" unless otherwise noted.
.LP
The overall configuration parameters available include:

.TP
\fBCount\fR
Number of resources of this type available on this node.
The default value is set to the number of \fBFile\fR values specified (if any),
otherwise the default value is one.

.TP
\fBCPUs\fR
Specify the CPU index numbers for the specific CPUs which can
use this resources. For example, it may be strongly preferable
to use specific CPUs with specific devices (e.g. on a NUMA
architecture). Multiple CPUs may be specified using a comma
delimited list or a range may be specified using a "\-" separator
(e.g. "0,1,2,3" or "0\-3").
If not specified, then any CPU can be used with the resources.
If any CPU can be used with the resources, then do not specify the
\fBCPUs\fR option for improved speed in the SLURM scheduling logic.

.TP
\fBFile\fR
Fully qualified pathname of the device files associated with a resource. 
The name can include a numberic range suffix to be interpretted by SLURM
(e.g. \fIFile=/dev/nvidia[0\-3]\fR).
This field is generally required if enforcement of generic resource
allocations is to be supported (i.e. prevents a users from making
use of resources allocated to a different user).
If \fBFile\fR is specified then \fBCount\fR must be either set to the number
of file names specified or not set (the default value is the number of files
specified).
NOTE: If you specify the \fBFile\fR parameter for a resource on some node,
the option must be specified on all nodes and SLURM will track the assignment
of each specific resource on each node. Otherwise SLURM will only track a
count of allocated resources rather than the state of each individual device
file.

.TP
\fBName\fR
Name of the generic resource. Any desired name may be used.
Each generic resource has an optional plugin which can provide
resource\-specific options.
Generic resources that currently include an optional plugin are:
.RS
.TP
\fBgpu\fR
Graphics Processing Unit
.TP
\fBnic\fR
Network Interface Card
.RE


.SH "EXAMPLE"
.LP
.br
##################################################################
.br
# SLURM's Generic Resource (GRES) configuration file
.br
##################################################################
.br
# Configure support for our four GPUs
.br
Name=gpu File=/dev/nvidia0 CPUs=0,1
.br
Name=gpu File=/dev/nvidia1 CPUs=0,1
.br
Name=gpu File=/dev/nvidia2 CPUs=2,3
.br
Name=gpu File=/dev/nvidia3 CPUs=2,3
.br
Name=bandwidth Count=20M

.SH "COPYING"
Copyright (C) 2010 The Regents of the University of California.
Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
CODE\-OCEC\-09\-009. All rights reserved.
.LP
This file is part of SLURM, a resource management program.
For details, see <https://computing.llnl.gov/linux/slurm/>.
.LP
SLURM is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 2 of the License, or (at your option)
any later version.
.LP
SLURM is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
details.

.SH "SEE ALSO"
.LP
\fBslurm.conf\fR(5)
