#! /bin/sh
#
# Setup ch_mpl
if [ -z "$DEVICE" ] ; then DEVICE=ch_mpl ; fi
for arg in $device_args $@ ; do
    case $arg in 
     -echo) set -x 
     ;;
     -u | -usage | --usage | --usag | --usa | --us | --u | -help | --help )
	echo "--with-device=$DEVICE" >&2
	exit 0;
	;;
     *) if test -n "$arg" ; then
	    echo "unrecognized argument $arg"
	    exit 1
	fi
	;;
    esac
done

# Check for ANL default machine:
if test -d /etc/FRAMES -a -d /mcs ; then
    DEFAULT_MACHINE="anlspx"
fi

# Run configure in the device directory
( cd mpid/ch_mpl ; export CC ; export MPILIBNAME ; \
    $top_srcdir/mpid/ch_mpl/configure )

