#! /bin/sh

# Set TSD by removing last slash and all that follows $0
TSD=`echo $0 | sed 's%/[^/][^/]*$%%'`
# Set TSD to be the absolute pathname to the top_srcdir
if [ "$TSD" = "$0" -o "X$TSD" = "X." ] ; then
    TSD=`pwd`
fi

configs=`find $TSD -name configure -print | grep -v profiling | sort`

for config in $configs ; do
    displayname=`echo $config | sed 's%^[^ ]*\/mpe%mpe%'`
    echo "****** Options available in $displayname"
    awk '/^ *--enable-[A-z]?.*\"$/ {print $0} \
         /^ *--with-[A-z]?.*\"$/ {print $0}' $config
    echo
done
