ClusterName=cluster
ControlMachine=node1
TopologyPlugin=topology/tree
TreeWidth=50
DebugFlags=Route
TopologyParam=RouteTree

# ================================
# Node and Partition Definitions
# ================================
NodeName=node[1-40]
PartitionName=all Nodes=node[1-40] Default=YES
